nameOverride: promops

##### grafana #####
grafana:
  enabled: false

##### prometheus-operator #####
prometheusOperator:
  priorityClassName: addons-critical
  createCustomResource: false
prometheus:
  podDisruptionBudget:
    enabled: true
  prometheusSpec:
    priorityClassName: addons-critical
    # QUESTION: enable to Prometheus scrape globally???
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  podDisruptionBudget:
    enabled: true
  alertmanagerSpec:
    priorityClassName: addons-critical

##### kube-state-metrics #####
kube-state-metrics:
  priorityClassName: addons-critical
  podSecurityPolicy:
    enabled: true
  # prometheus.monitor.enabled

##### prometheus-node-exporter #####
prometheus-node-exporter:
  priorityClassName: addons-critical
  # prometheus.monitor.enabled
