apiVersion: v1
kind: Service
metadata:
  name: {{ include "hdfs.fullname" . }}-namenode
  labels:
    {{- include "hdfs.namenode.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: rpc
    port: 8020
    targetPort: rpc
    protocol: TCP
  - name: http
    port: 9870
    targetPort: http
    protocol: TCP
  selector:
    {{- include "hdfs.namenode.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: true
