apiVersion: v1
kind: Secret
metadata:
  name: cilium-clustermesh
  namespace: kube-system
type: Opaque
stringData:
  compute: |
    endpoints:
      - https://kitlab.dungdm93.local:2379

    trusted-ca-file: /var/lib/cilium/clustermesh/client/ca.crt
    cert-file:       /var/lib/cilium/clustermesh/client/tls.crt
    key-file:        /var/lib/cilium/clustermesh/client/tls.key
