{{- $httpServer := .Values.httpServer }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "presto.fullname" . }}
  labels:
    {{- include "presto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if $httpServer.http.enabled }}
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  {{- end }}
  {{- if $httpServer.https.enabled }}
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
  {{- end }}
  selector:
    {{- include "presto.coordinator.selectorLabels" . | nindent 4 }}
