apiVersion: v2
name: hive-metastore
description: hive-metastore helm chart
icon: https://upload.wikimedia.org/wikipedia/commons/b/bb/Apache_Hive_logo.svg
type: application
version: 0.1.0
appVersion: 3.1.2
# kubeVersion: ^1.15
dependencies:
- name: postgresql
  version: 8.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
maintainers:
- name: Teko's DataOps team
  email: dataops@teko.vn
