nameOverride: ""
fullnameOverride: ""

image:
  repository: hub.teko.vn/data/hive
  tag: 3.1.2-hadoop-3.1.0
  pullPolicy: IfNotPresent
  pullSecrets: []
  # - name: regcred

hiveConfig:
  path: /opt/hive/conf/
  hive-site.xml: {}

hadoopConfig:
  path: /opt/hadoop/etc/hadoop/
  hdfs-site.xml: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
podSecurityContext: {}
  # fsGroup: 2000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Placement
affinity: {}
tolerations: []
nodeSelector: {}

postgresql:
  enabled: true

  postgresqlUsername: postgres
  postgresqlPassword: hive-metastore
  postgresqlDatabase: hive-metastore

  replication:
    enabled: false

  persistence:
    enabled: true

externalDatabase:
  type:
  url:
  host:
  port:
  database:
  username:
  password:

warehouse:
  dir:

filesystem:
  ## Hadoop HDFS
  hdfs:

  ## Amazon S3
  ## https://hadoop.apache.org/docs/current/hadoop-aws/tools/hadoop-aws/index.html
  s3a:

  ## Google Cloud Storage
  ## https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/gcs/CONFIGURATION.md
  gcs:

  ## Microsoft Azure Blob Storage
  ## https://hadoop.apache.org/docs/current/hadoop-azure/index.html
  wasbs:

  ## Microsoft Azure Data Lake
  ## https://hadoop.apache.org/docs/current/hadoop-azure-datalake/index.html
  adl:

  ## OpenStack Swift
  ## https://hadoop.apache.org/docs/current/hadoop-openstack/index.html
  swift:

  ## Alibaba Aliyun OSS
  ## https://hadoop.apache.org/docs/current/hadoop-aliyun/tools/hadoop-aliyun/index.html
  oss:

serviceAccount:
  create: true
  annotations: {}
  name:

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
