---
- name: restart docker
  listen: restart_docker
  ansible.builtin.systemd:
    name:  docker.service
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart containerd
  listen: restart_containerd
  ansible.builtin.systemd:
    name:  containerd.service
    state: restarted
    enabled: yes
    daemon_reload: yes
