{{- $flower := mergeOverwrite (deepCopy .Values.commons) .Values.flower -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airflow.fullname" . }}-flower
  labels:
    {{- include "airflow.flower.labels" . | nindent 4 }}
  annotations:
    {{- toYaml $flower.annotations | nindent 4 }}
spec:
  replicas: {{ $flower.replicas }}
  selector:
    matchLabels:
      {{- include "airflow.flower.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "airflow.flower.selectorLabels" . | nindent 8 }}
      annotations:
        {{- with $flower.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "airflow.checksum" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      enableServiceLinks: false
      containers:
        - name: flower
          image: "{{ $flower.image.repository }}:{{ $flower.image.tag }}"
          imagePullPolicy: {{ $flower.imagePullPolicy }}
        {{- with $flower.command }}
          command:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with $flower.args }}
          args:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          env:
            {{- toYaml $flower.env | nindent 12 }}
          envFrom:
            - configMapRef:
                name: "{{ template "airflow.fullname" . }}-env"
          ports:
          - name: web
            protocol: TCP
            containerPort: 8080
          volumeMounts: {}
          livenessProbe:
            httpGet:
              path: /health
              port: web
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: web
            periodSeconds: 30
          resources:
            {{- toYaml $flower.resources | nindent 12 }}
      serviceAccountName: {{ include "airflow.serviceAccountName" . }}
      priorityClassName:  {{ $flower.priorityClassName }}
      runtimeClassName:   {{ $flower.runtimeClassName }}
      schedulerName:      {{ $flower.schedulerName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if .Values.volumes }}
      volumes:
        {{- include "generic.volumes" . | nindent 8 }}
    {{- end }}
    {{- with $flower.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $flower.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $flower.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
