{{- $flower := mergeOverwrite (deepCopy .Values.commons) .Values.flower -}}
{{- if eq (include "airflow.normalizeExecutor" .) "CeleryExecutor" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airflow.fullname" . }}-flower
  labels:
    {{- include "airflow.flower.labels" . | nindent 4 }}
    {{- with $flower.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml $flower.annotations | nindent 4 }}
spec:
  replicas: {{ $flower.replicas }}
  selector:
    matchLabels:
      {{- include "airflow.flower.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "airflow.flower.selectorLabels" . | nindent 8 }}
        {{- with $flower.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- include "airflow.checksum" . | nindent 8 }}
        {{- with $flower.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableServiceLinks: false
      containers:
        - name: airflow-flower
          image: "{{ $flower.image.repository }}:{{ $flower.image.tag }}"
          imagePullPolicy: {{ $flower.imagePullPolicy }}
          {{- with $flower.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $flower.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- toYaml $flower.env | nindent 12 }}
          # envFrom:
          #   - configMapRef:
          #       name: "{{ template "airflow.fullname" . }}-env"
          ports:
            - name: flower
              protocol: TCP
              containerPort: 5555
          volumeMounts:
            - name: airflow-config
              mountPath: /opt/airflow/airflow.cfg
              subPath:   airflow.cfg
          livenessProbe:
            httpGet:
              path: /
              port: flower
            periodSeconds: 30
          resources:
            {{- toYaml $flower.resources | nindent 12 }}
          securityContext:
            {{- toYaml $flower.securityContext | nindent 12 }}
      serviceAccountName: {{ include "airflow.flower.serviceAccountName" . }}
      priorityClassName:  {{ $flower.priorityClassName }}
      runtimeClassName:   {{ $flower.runtimeClassName }}
      schedulerName:      {{ $flower.schedulerName }}
      securityContext:
        {{- toYaml $flower.podSecurityContext | nindent 8 }}
      volumes:
        - name: airflow-config
          configMap:
            name: {{ include "airflow.fullname" . }}-config
      {{- with $flower.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $flower.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $flower.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
