{{- $flower := mergeOverwrite (deepCopy .Values.commons) .Values.flower -}}
{{- if and (eq (include "airflow.normalizeExecutor" .) "CeleryExecutor") $flower.ingress.enabled }}
{{- $flowerService := printf "%s-flower" (include "airflow.fullname" .) -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "airflow.fullname" . }}-flower
  labels:
    {{- include "airflow.flower.labels" . | nindent 4 }}
  annotations:
    {{- toYaml $flower.ingress.annotations | nindent 4 }}
spec:
  {{- if hasKey $flower.ingress "ingressClassName" }}
  ingressClassName: {{ $flower.ingress.ingressClassName }}
  {{- end }}
  {{- if $flower.ingress.tls }}
  tls:
  {{- range $flower.ingress.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
  {{- range $flower.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      - path: {{ .path | default "/flower" }}
        pathType: {{ .pathType | default "Prefix" }}
        backend:
          service:
            name: {{ $flowerService }}
            port:
              name: flower
  {{- end }}
{{- end }}
