{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "airflow.flower.serviceAccountName" . }}
  labels:
    {{- include "airflow.flower.labels" . | nindent 4 }}
{{- end }}
