{{- $flower := mergeOverwrite (deepCopy .Values.commons) .Values.flower -}}
{{- if eq .Values.airflow.core.executor "CeleryExecutor" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow.fullname" . }}-flower
  labels:
    {{- include "airflow.flower.labels" . | nindent 4 }}
  annotations:
    {{- toYaml $flower.service.annotations | nindent 4 }}
spec:
  type: {{ $flower.service.type }}
  ports:
    - port: {{ $flower.service.port }}
      name: flower
      protocol: TCP
      {{- if eq $flower.service.type "NodePort" }}
      nodePort: {{ $flower.service.nodePort }}
      {{- end }}
      targetPort: flower
  selector:
    {{- include "airflow.flower.selectorLabels" . | nindent 4 }}
{{- end }}
