{{- $runtime := index .Values.druid.broker "runtime.properties" | default dict }}
{{- $jvm := index .Values.druid.broker "jvm.config" }}
{{- $extraJvm := index .Values.druid.broker "extra.jvm.config" }}
{{- $config := omit .Values.druid.broker "runtime.properties" "jvm.config" "extra.jvm.config" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "druid.fullname" . }}-broker
  labels:
    {{- include "druid.broker.labels" . | nindent 4 }}
data:
  runtime.properties: |
    {{- range $key, $value := $runtime }}
    {{ $key }}={{ has (kindOf $value) (list "map" "slice") | ternary (mustToJson $value) $value }}
    {{- end }}

  jvm.config: |
    {{ $jvm | nindent 4 | trim }}
    {{- if $extraJvm }}
    {{ $extraJvm | nindent 4 | trim }}
    {{- end }}

  {{- range $file, $content := $config }}
  {{ $file }}: |
    {{ $content | nindent 4 | trim }}
  {{- end }}
