{{- $runtime := index .Values.druid.broker "runtime.properties" | default dict }}
{{- $config := omit .Values.druid.broker "runtime.properties" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "druid.fullname" . }}-broker
  labels:
    {{- include "druid.broker.labels" . | nindent 4 }}
data:
  runtime.properties: |
    {{- range $key, $value := $runtime }}
    {{ $key }}={{ has (kindOf $value) (list "map" "slice") | ternary (mustToJson $value) $value }}
    {{- end }}

  {{- range $file, $content := $config }}
  {{ $file }}: |
    {{ $content | nindent 4 | trim }}
  {{- end }}
