{{- $broker := mergeOverwrite (deepCopy .Values.commons) .Values.broker -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "druid.fullname" . }}-broker
  labels:
    {{- include "druid.broker.labels" . | nindent 4 }}
    {{- with $broker.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml $broker.annotations | nindent 4 }}
spec:
  replicas: {{ $broker.replicas }}
  selector:
    matchLabels:
      {{- include "druid.broker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "druid.broker.selectorLabels" . | nindent 8 }}
        {{- with $broker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- include "druid.broker.checksum" . | nindent 8 }}
        {{- with $broker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      enableServiceLinks: false
      containers:
        - name: druid-broker
          image: {{ include "druid.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with $broker.command }}
          command:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with $broker.args }}
          args:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          env:
            {{- toYaml $broker.env | nindent 12 }}
          ports:
            - name: http
              protocol: TCP
              containerPort: 8082
          {{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion }}
          startupProbe:
            httpGet:
              port: http
              path: /status/health
            periodSeconds: 10
            failureThreshold: 30  # total 5m
          {{- end }}
          livenessProbe:
            httpGet:
              port: http
              path: /status/health
          readinessProbe:
            httpGet:
              port: http
              path: /status/selfDiscovered
          volumeMounts:
            {{- include "druid.broker.volumeMounts" . | nindent 12 }}
          resources:
            {{- toYaml $broker.resources | nindent 12 }}
          securityContext:
            {{- toYaml $broker.securityContext | nindent 12 }}
      serviceAccountName: {{ include "druid.broker.serviceAccountName" . }}
      priorityClassName:  {{ $broker.priorityClassName }}
      runtimeClassName:   {{ $broker.runtimeClassName }}
      schedulerName:      {{ $broker.schedulerName }}
      securityContext:
        {{- toYaml $broker.podSecurityContext | nindent 8 }}
      volumes:
        {{- include "druid.broker.volumes" . | nindent 8 }}
    {{- with $broker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $broker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $broker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
