{{- if and .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "druid.broker.serviceAccountName" . }}
  labels:
    {{- include "druid.broker.labels" . | nindent 4 }}
{{- end }}
