---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "druid.fullname" . }}-broker
  labels:
    {{- include "druid.broker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8082
    protocol: TCP
    targetPort: http
  selector:
    {{- include "druid.broker.selectorLabels" . | nindent 4 }}
