{{- $webserver := mergeOverwrite (deepCopy .Values.commons) .Values.webserver -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "superset.fullname" . }}-webserver
  labels:
    {{- include "superset.webserver.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: web
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: web
  selector:
    {{- include "superset.webserver.selectorLabels" . | nindent 4 }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  sessionAffinityConfig:
    {{- toYaml .Values.service.sessionAffinityConfig | nindent 4 }}
