---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.fullname" . }}-read
  labels:
    {{- include "loki.read.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "loki.read.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 3100
    targetPort: http
    protocol: TCP
    appProtocol: http
  - name: grpc
    port: 9095
    targetPort: grpc
    protocol: TCP
    appProtocol: gRPC
---
{{- if .Values.read.stateful }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.fullname" . }}-read-headless
  labels:
    {{- include "loki.read.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "loki.read.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 3100
    targetPort: http
    protocol: TCP
    appProtocol: http
  - name: grpc
    port: 9095
    targetPort: grpc
    protocol: TCP
    appProtocol: gRPC
{{- end }}
