{{- $gms := mergeOverwrite (deepCopy .Values.commons) .Values.gms -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "datahub.fullname" . }}-system-update
  labels:
    {{- include "datahub.labels" . | nindent 4 }}
    app.kubernetes.io/component: system-update
    {{- with $gms.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "5"
spec:
  template:
    metadata:
      labels:
        {{- include "datahub.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: system-update
        {{- with $gms.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $gms.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with $gms.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableServiceLinks: false
      restartPolicy: Never
      containers:
        - name: datahub-system-update
          image: "{{ .Values.setup.systemUpdate.image.repository }}:{{ .Values.setup.systemUpdate.image.tag }}"
          imagePullPolicy: {{ $gms.image.pullPolicy }}
          args: [-u, SystemUpdate]
          envFrom:
          - secretRef:
              name: {{ include "datahub.fullname" . }}-hooks
          securityContext:
            {{- toYaml $gms.securityContext | nindent 12 }}
      priorityClassName:  {{ $gms.priorityClassName }}
      runtimeClassName:   {{ $gms.runtimeClassName }}
      schedulerName:      {{ $gms.schedulerName }}
      securityContext:
        {{- toYaml $gms.podSecurityContext | nindent 8 }}
      {{- with $gms.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $gms.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $gms.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $gms.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
