{{- $airflow := .Values.airflow }}
{{- $core := (dict "core" dict | mergeOverwrite $airflow).core }}
{{- $database := (dict "database" dict | mergeOverwrite $airflow).database }}
{{- $logging := (dict "logging" dict | mergeOverwrite $airflow).logging }}
{{- $celery := (dict "celery" dict | mergeOverwrite $airflow).celery }}
{{- $kubernetes := (dict "kubernetes" dict | mergeOverwrite $airflow).kubernetes }}
{{- $elasticsearch := (dict "elasticsearch" dict | mergeOverwrite $airflow).elasticsearch }}

{{- $_ := set $core "executor"  (include "airflow.normalizeExecutor" .) }}
{{- $_ := set $core "fernet_key" .Values.fernetKey }}

{{- $logs := .Values.logs }}
{{- $dags := .Values.dags }}

{{- $_ := set $core "dags_folder" (include "airflow.dags.folder" $dags) }}
{{- $_ := set $core "donot_pickle" $dags.doNotPickle }}

{{- $_ := set $database "sql_alchemy_conn" (include "airflow.database" .) }}

{{- $_ := set $logging "logging_level" $logs.level }}
{{- $_ := set $logging "base_log_folder" $logs.baseLogFolder }}
{{- if $logs.remoteLogConnId }}
  {{- $_ := set $logging "remote_logging" true }}
  {{- $_ := set $logging "remote_log_conn_id" $logs.remoteLogConnId }}
  {{- $_ := set $logging "remote_base_log_folder" $logs.remoteBaseLogFolder }}
{{- end }}

{{- if eq $core.executor "CeleryExecutor" }}
  {{- $_ := set $celery "broker_url" (include "airflow.celeryBroker" .) }}
  {{- if not $celery.result_backend }}
    {{- $_ := set $celery "result_backend" (include "airflow.celeryResultBackend" .) }}
  {{- end }}
{{- end }}

{{- if eq $core.executor "KubernetesExecutor" }}
  {{- $worker := mergeOverwrite (deepCopy .Values.commons) .Values.worker -}}

  {{- $_ := set $kubernetes "in_cluster"                         true                     }}
  {{- $_ := set $kubernetes "namespace"                          .Release.Namespace       }}
  {{- $_ := set $kubernetes "worker_container_repository"        $worker.image.repository }}
  {{- $_ := set $kubernetes "worker_container_tag"               $worker.image.tag        }}
  {{- $_ := set $kubernetes "worker_container_image_pull_policy" .Values.imagePullPolicy  }}
  {{- $_ := set $kubernetes "image_pull_secrets" (include "join-transform" (list "," .Values.imagePullSecrets ".name")) }}
  {{- $_ := set $kubernetes "worker_service_account_name" (include "airflow.worker.serviceAccountName" .) }}
  {{- $_ := set $kubernetes "worker_annotations"          (toJson $worker.podAnnotations) }}

  {{- $_ := set $kubernetes "airflow_configmap" (printf "%s-config" (include "airflow.fullname" .)) }}
  {{- $_ := set $kubernetes "airflow_local_settings_configmap" (printf "%s-config" (include "airflow.fullname" .)) }}
  # env_from_configmap_ref
  # env_from_secret_ref

  # DAGs
  {{- if eq $dags.fetcher "none" }}
    {{- $_ := set $kubernetes "dags_in_image" true }}
  {{- else if eq $dags.fetcher "git" }}
    {{- $_ := set $kubernetes "dags_in_image" false }}
    {{- $gitsync := $dags.git -}}

    {{- $_ := set $kubernetes "git_repo"    $gitsync.repo    }}
    {{- $_ := set $kubernetes "git_branch"  $gitsync.branch  }}
    {{- $_ := set $kubernetes "git_subpath" $gitsync.subPath }}
    {{- $_ := set $kubernetes "git_dags_folder_mount_point" $dags.path }}

    {{- if $gitsync.auth.username }}
      {{- $_ := set $kubernetes "git_sync_credentials_secret" (printf "%s-gitsync" (include "airflow.fullname" .)) }}
    {{- else if $gitsync.auth.sshKey }}
      {{- $_ := set $kubernetes "git_ssh_key_secret_name" (printf "%s-gitsync-sshkey" (include "airflow.fullname" .)) }}
    {{- else if $gitsync.auth.externalSshKeySecret.name }}
      {{- $_ := set $kubernetes "git_ssh_key_secret_name" $gitsync.auth.externalSshKeySecret.name }}
      {{- if not (eq ($gitsync.auth.externalSshKeySecret.key | default "gitSshKey") "gitSshKey")}}
        {{- fail "Custom externalSshKeySecret.key is not support by KubernetesExecutor yet" }}
      {{- end }}
    {{- end }}
  {{- else if eq $dags.fetcher "volume" }}
    {{- $_ := set $kubernetes "dags_in_image" false }}

    {{- $_ := set $kubernetes "dags_volume_claim" ($dags.volume.existingClaim | default (printf "%s-dags" (include "airflow.fullname" .))) }}
    {{- $_ := set $kubernetes "dags_volume_subpath" $dags.volume.subPath }}
  {{- end }}

  # Logs
  {{- if and (not $logs.remoteLogConnId) $logs.persistence.enabled }}
    {{- $_ := set $kubernetes "logs_volume_claim" ($logs.persistence.existingClaim | default (printf "%s-logs" (include "airflow.fullname" .))) }}
    {{- $_ := set $kubernetes "logs_volume_subpath" $logs.persistence.subPath }}
  {{- end }}

  # Placement
  {{- with $worker.affinity }}
    {{- $_ := set $kubernetes "affinity" (toJson .) }}
  {{- end }}
  {{- with $worker.tolerations }}
    {{- $_ := set $kubernetes "tolerations" (toJson .) }}
  {{- end }}
  {{- with $worker.nodeSelector }}
    {{- $_ := dict "kubernetes_node_selectors" . | mergeOverwrite $airflow }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "airflow.fullname" . }}-config
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
data:
  airflow.cfg: |
{{- range $key, $value := $airflow }}
  {{- if $value }}
    [{{ $key }}]
    {{- range $elem, $elemVal := $value }}
    {{ $elem }} = {{ $elemVal }}
    {{- end }}
  {{- end }}
{{ end }}

  webserver_config.py: |
    {{ .Values.webserver_config | nindent 4 | trim }}

  airflow_local_settings.py: |
    {{ .Values.airflow_local_settings | nindent 4 | trim }}
