apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "airflow.fullname" . }}-probes
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
data:
  scheduler_liveness_probe.sh: |
    #!/usr/bin/env bash
    export CONNECTION_CHECK_MAX_COUNT=0
    export AIRFLOW__LOGGING__LOGGING_LEVEL=ERROR

    exec airflow jobs check --job-type SchedulerJob --local

  triggerer_liveness_probe.sh: |
    #!/usr/bin/env bash
    export CONNECTION_CHECK_MAX_COUNT=0
    export AIRFLOW__LOGGING__LOGGING_LEVEL=ERROR

    exec airflow jobs check --job-type TriggererJob --local

  worker_liveness_probe.sh: |
    #!/usr/bin/env bash
    exec celery -A airflow.executors.celery_executor.app inspect ping -d celery@$HOSTNAME -t 5.0
