{{- $logs  := .Values.logs -}}
{{- if and $logs.persistence.enabled (not $logs.persistence.existingClaim) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "airflow.fullname" . }}-logs
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
spec:
{{- if kindIs "invalid" $logs.persistence.storageClass }}
  # storageClass is null, using default provisioner
{{- else if or (empty $logs.persistence.storageClass) (eq "-" $logs.persistence.storageClass) }}
  storageClassName: "" # disables dynamic provisioning
{{- else }}
  storageClassName: {{ $logs.persistence.storageClass }}
{{- end }}
  resources:
    requests:
      storage: {{ $logs.persistence.size }}
  accessModes:
    - {{ $logs.persistence.accessMode }}
  volumeMode: Filesystem
{{- end }}
