{{- if .Values.rbac.create }}
{{- $executor := include "airflow.normalizeExecutor" . }}
{{- $grantScheduler := or (eq $executor "LocalExecutor") (eq $executor "SequentialExecutor") (eq $executor "KubernetesExecutor") }}
{{- $grantWorker := or (eq $executor "CeleryExecutor") (eq $executor "KubernetesExecutor") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "airflow.fullname" . }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["create", "get", "delete", "list", "watch"]
- apiGroups: [""]
  resources:
  - "pods/log"
  verbs: ["get", "list"]
- apiGroups: [""]
  resources:
  - "pods/exec"
  verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "airflow.fullname" . }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "airflow.fullname" . }}
subjects:
{{- if $grantScheduler }}
- kind: ServiceAccount
  name: {{ include "airflow.scheduler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- if $grantWorker }}
- kind: ServiceAccount
  name: {{ include "airflow.worker.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
