{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "airflow.serviceAccountName" . }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
{{- end }}
