{{- $kind := lower .Values.app.kind -}}
apiVersion: apps/v1
{{- if eq $kind "deployment"  }}
kind: Deployment
{{- else if eq $kind "statefulset"  }}
kind: StatefulSet
{{- else }}
{{- fail (printf "unknow kind %s" $kind) }}
{{- end }}
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.app.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  {{- if eq $kind "statefulset"  }}
  serviceName: {{ include "generic.fullname" . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "generic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "generic.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
        checksum/secret:    {{ include (print $.Template.BasePath "/secrets.yaml") .    | sha256sum }}
        {{- with .Values.app.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      enableServiceLinks: false
      containers:
        - name:  app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.app.command }}
          command:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.app.args }}
          args:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- if .Values.env }}
          env:
            {{- include "generic.env" . | nindent 12 }}
        {{- end }}
        {{- if .Values.envFrom }}
          envFrom:
            {{- include "generic.envFrom" . | nindent 12 }}
        {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
        {{- if .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
        {{- end }}
        {{- if .Values.volumeDevices }}
          volumeDevices:
            {{- toYaml .Values.volumeDevices | nindent 12 }}
        {{- end }}
        {{- with .Values.app.healthcheck.liveness }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.app.healthcheck.readiness }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.app.healthcheck.startup }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      serviceAccountName: {{ include "generic.serviceAccountName" . }}
      priorityClassName:  {{ .Values.app.priorityClassName }}
      runtimeClassName:   {{ .Values.app.runtimeClassName }}
      schedulerName:      {{ .Values.app.schedulerName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if .Values.volumes }}
      volumes:
        {{- include "generic.volumes" . | nindent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
