{{- $backend := mergeOverwrite (deepCopy .Values.commons) .Values.backend -}}
{{- $service := $backend.service -}}
{{- $specifyNodePort := or (eq $service.type "NodePort") (and (eq $service.type "LoadBalancer") $service.allocateLoadBalancerNodePorts) -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir.fullname" . }}-backend
  labels:
    {{- include "mimir.backend.labels" . | nindent 4 }}
  {{- with $service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $service.type }}
  {{- with $service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- if eq $service.type "LoadBalancer" }}
  {{- with $service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with $service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  {{- if not $service.allocateLoadBalancerNodePorts }}
  allocateLoadBalancerNodePorts: false
  {{- end }}
  {{- end }}
  {{- with $service.internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with $service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with $service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  {{- with $service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "mimir.backend.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 9009
    targetPort: http
    protocol: TCP
    appProtocol: http
    {{- if and $specifyNodePort $service.nodePorts.http }}
    nodePort: {{ $service.nodePorts.http }}
    {{- end }}
  - name: grpc
    port: 9095
    targetPort: grpc
    protocol: TCP
    appProtocol: gRPC
    {{- if and $specifyNodePort $service.nodePorts.grpc }}
    nodePort: {{ $service.nodePorts.grpc }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir.fullname" . }}-backend-headless
  labels:
    {{- include "mimir.backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "mimir.backend.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 9009
    targetPort: http
    protocol: TCP
    appProtocol: http
  - name: grpc
    port: 9095
    targetPort: grpc
    protocol: TCP
    appProtocol: gRPC
