{{- $backend := mergeOverwrite (deepCopy .Values.commons) .Values.backend -}}
{{- $persistence := $backend.persistence -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mimir.fullname" . }}-backend
  labels:
    {{- include "mimir.backend.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: memberlist
    {{- with $backend.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml $backend.annotations | nindent 4 }}
spec:
  replicas: {{ $backend.replicas }}
  serviceName: "{{ include "mimir.fullname" . }}-backend-headless"
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "mimir.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mimir.backend.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/part-of: memberlist
        {{- with $backend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- include "mimir.checksum" . | nindent 8 }}
        {{- with $backend.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableServiceLinks: false
      terminationGracePeriodSeconds: {{ $backend.terminationPeriod }}
      containers:
        - name: mimir-backend
          image: {{ include "mimir.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -target={{ $backend.target | join "," }}
            - -config.file=/etc/mimir/config.yaml
            {{- with .Values.backend.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with $backend.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $backend.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.config.server.http_listen_port }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.config.server.grpc_listen_port }}
              protocol: TCP
            - name: memberlist
              containerPort: {{ .Values.ringKVStore.memberlist.bind_port }}
              protocol: TCP
          volumeMounts:
            {{- include "mimir.volumeMounts" . | nindent 12 }}
            - name: data
              mountPath: /mimir/
            {{- with $backend.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /api/v1/status/buildinfo
              port: http
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            periodSeconds: 30
          {{- with $backend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $backend.securityContext }}
          securityContext:
            {{- toYaml . | nindent 8 }}
          {{- end }}
      serviceAccountName: {{ include "mimir.serviceAccountName" . }}
      priorityClassName:  {{ $backend.priorityClassName }}
      runtimeClassName:   {{ $backend.runtimeClassName }}
      schedulerName:      {{ $backend.schedulerName }}
      {{- with $backend.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- include "mimir.volumes" . | nindent 8 }}
        {{- if not $persistence.enabled }}
        - name: data
          emptyDir: {}
        {{- end }}
        {{- with $backend.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if $persistence.enabled }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        name: data
        {{- with $persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        volumeMode: Filesystem
        accessModes: [ReadWriteOnce]
        {{- with $persistence.storageClass }}
        storageClassName: {{ eq "-" . | ternary "" . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ $persistence.size | quote }}
        {{- with $persistence.selector }}
        selector:
          {{- toYaml . | nindent 10 }}
        {{- end }}
  {{- end }}
