apiVersion: v2
name: superset
description: Superset helm chart
icon: https://github.com/apache/superset/raw/master/docs/src/images/s.png
type: application
version: 0.1.0
appVersion: 1.0.0
# kubeVersion: ^1.15
dependencies:
- name: postgresql
  version: 10.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 12.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
maintainers:
- name: Teko's DataOps team
  email: dataops@teko.vn
