apiVersion: v2
name: superset
description: Superset helm chart
icon: https://github.com/apache/superset/raw/master/docs/src/images/s.png
type: application
version: 1.1.1
appVersion: 2.1.0
# kubeVersion: ^1.19
dependencies:
- name: postgresql
  version: 12.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 17.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
maintainers:
- name: Đặng Minh Dũng
  email: hello@dungdm93.me
