---
- name: restart systemd-modules-load
  listen: restart_systemd-modules-load
  ansible.builtin.systemd:
    name:  systemd-modules-load.service
    state: restarted

- name: restart time service
  listen: restart_time
  ansible.builtin.systemd:
    name:  "{{time.service}}"
    state: restarted

- name: restart domain service
  listen: restart_domain
  ansible.builtin.systemd:
    name:  systemd-resolved.service
    state: restarted
