apiVersion: v1
kind: Secret
metadata:
  name: ceph-csi-cephfs-provisioner
  namespace: kube-system
# type: kubernetes.io/rook
stringData:
  adminID:  csi-cephfs-provisioner
  adminKey: <csi-cephfs-provisioner-admin-key>
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-csi-cephfs-node
  namespace: kube-system
# type: kubernetes.io/rook
stringData:
  adminID:  csi-cephfs-node
  adminKey: <csi-cephfs-node-admin-key>
