# https://github.com/ceph/ceph-csi/blob/master/examples/cephfs/storageclass.yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cephfs
provisioner: cephfs.csi.ceph.com
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  clusterID: rook-ceph
  fsName: cephfs

  csi.storage.k8s.io/provisioner-secret-name: ceph-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/controller-expand-secret-name: ceph-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: ceph-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
