image:
  repository: hub.teko.vn/data/spark
  tag: 2.4.4-hadoop-3.2.1
  pullPolicy: IfNotPresent

app:
  replicas: 1
  command:
  - spark
  - history-server

configMaps:
- name: configs
  data:
    foo: bar
    abc: xyz
- name: abcxyz
  data:
    first: 1
    second: 2

secrets:
- name: credential
  type: Opaque
  stringData:
    username: admin
  data:
    password: Zm9vYmFyCg==  # base64 encoded string
