apiVersion: v2
name: druid
description: Druid helm chart
icon: https://raw.githubusercontent.com/apache/druid/druid-0.21.0/web-console/assets/druid.png
type: application
version: 0.1.1
appVersion: 0.21.0
dependencies:
- name: zookeeper
  version: 6.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: zookeeper.enabled
- name: postgresql
  version: 10.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
maintainers:
- name: Teko's DataOps team
  email: dataops@teko.vn
