replicas: 3
priorityClassName: addons-critical

serviceAccount:
  create: true

rbac:
  create: true
  pspEnabled: true

podDisruptionBudget:
  minAvailable: 1

networkPolicy:
  enabled: false

serviceMonitor:
  enabled: true

tracing:
  jaegerAgentHost:
