config:
  schema_config:
    configs:
    - store: boltdb
      object_store: filesystem
      schema: v9
      index:
        prefix: index_
      chunks:
        prefix: chunks_
  storage_config:
    boltdb:
      directory: /data/loki/index
    filesystem:
      directory: /data/loki/chunks
  table_manager:
    retention_deletes_enabled: true
    retention_period: 360h # 15days

persistence:
  enabled: false
