{{- $triggerer := mergeOverwrite (deepCopy .Values.commons) .Values.triggerer -}}
{{- if and .Values.serviceAccount.create (eq (include "airflow.normalizeExecutor" .) "CeleryExecutor") }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "airflow.triggerer.serviceAccountName" . }}
  labels:
    {{- include "airflow.triggerer.labels" . | nindent 4 }}
{{- end }}
