{{- $triggerer := mergeOverwrite (deepCopy .Values.commons) .Values.triggerer -}}
{{- if eq (include "airflow.normalizeExecutor" .) "CeleryExecutor" }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "airflow.fullname" . }}-triggerer
  labels:
    {{- include "airflow.triggerer.labels" . | nindent 4 }}
    {{- with $triggerer.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml $triggerer.annotations | nindent 4 }}
spec:
  replicas: {{ $triggerer.replicas }}
  serviceName: "{{ template "airflow.fullname" . }}-triggerer"
  podManagementPolicy: Parallel
  updateStrategy:
    ## Kill the triggerers as soon as possible, the scheduler will restart the failed jobs later
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "airflow.triggerer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "airflow.triggerer.selectorLabels" . | nindent 8 }}
        {{- with $triggerer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- include "airflow.checksum" . | nindent 8 }}
        {{- with $triggerer.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableServiceLinks: false
      terminationGracePeriodSeconds: {{ $triggerer.terminationPeriod }}
      initContainers:
      {{- if eq .Values.dags.fetcher "git" }}
        {{- include "airflow.gitsync.init" . | nindent 8 }}
      {{- end }}
      containers:
        - name: airflow-triggerer
          image: "{{ $triggerer.image.repository }}:{{ $triggerer.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- with $triggerer.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $triggerer.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- toYaml $triggerer.env | nindent 12 }}
          # envFrom:
          #   - configMapRef:
          #       name: "{{ template "airflow.fullname" . }}-env"
          volumeMounts:
            {{- include "airflow.volumeMounts" . | nindent 12 }}
            {{- with $triggerer.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            periodSeconds: 30
            timeoutSeconds: 10
            exec:
              command:
              - bash
              - /opt/airflow/scripts/triggerer_liveness_probe.sh
          resources:
            {{- toYaml $triggerer.resources | nindent 12 }}
          securityContext:
            {{- toYaml $triggerer.securityContext | nindent 12 }}
        {{- if eq .Values.dags.fetcher "git" }}
        {{- include "airflow.gitsync.sidecar" . | nindent 8 }}
        {{- end }}
        {{- include "airflow.logGroomer.sidecar" . | nindent 8 }}
      serviceAccountName: {{ include "airflow.triggerer.serviceAccountName" . }}
      priorityClassName:  {{ $triggerer.priorityClassName }}
      runtimeClassName:   {{ $triggerer.runtimeClassName }}
      schedulerName:      {{ $triggerer.schedulerName }}
      securityContext:
        {{- toYaml $triggerer.podSecurityContext | nindent 8 }}
      volumes:
        {{- include "airflow.volumes" . | nindent 8 }}
      {{- with $triggerer.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $triggerer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $triggerer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $triggerer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
