apiVersion: v1
kind: Secret
metadata:
  name: ceph-csi-rbd-provisioner
  namespace: kube-system
# type: kubernetes.io/rook
stringData:
  userID:  csi-rbd-provisioner
  userKey: <csi-rbd-provisioner-user-key>
---
apiVersion: v1
kind: Secret
metadata:
  name: ceph-csi-rbd-node
  namespace: kube-system
# type: kubernetes.io/rook
stringData:
  userID:  csi-rbd-node
  userKey: <csi-rbd-node-user-key>
