repositories:
- name: grafana
  url:  https://grafana.github.io/helm-charts

releases:
- name: grafana-oncall
  namespace: grafana-oncall
  chart: grafana/oncall
  version: 1.1.0
  values:
  - ./grafana-oncall.yaml.gotmpl
  - fullnameOverride: grafana-oncall
