apiVersion: v1
kind: Secret
metadata:
  name: grafana-oncall
  namespace: grafana-oncall
  labels:
    app.kubernetes.io/name: oncall
    app.kubernetes.io/instance: grafana-oncall
type: Opaque
stringData:
  SECRET_KEY: my_random_secret_must_be_more_than_32_characters_long
  MIRAGE_SECRET_KEY: my_random_secret_must_be_more_than_32_characters_long
