image:
  repository: ghcr.io/googlecloudplatform/spark-operator
  tag: v1beta2-1.3.8-3.1.1

rbac:
  create: true
  createRole: true
  createClusterRole: true

serviceAccounts:
  spark:
    create: true
    name: spark
  sparkoperator:
    create: true

sparkJobNamespace: spark

uiService:
  enable: true

webhook:
  enable: true

batchScheduler:
  enable: false

resourceQuotaEnforcement:
  enable: false

podMonitor:
  enable: true
  podMetricsEndpoint:
    interval: 10s
