repositories:
- name: prometheus-community
  url:  https://prometheus-community.github.io/helm-charts

releases:
- name: kube-state-metrics
  namespace: grafana-agent
  chart: prometheus-community/kube-state-metrics
  version: 4.25.0
  values:
  - ./kube-state-metrics.yaml.gotmpl
  - fullnameOverride: kube-state-metrics
