{{- $trino := .Values.trino }}
{{- $config := index $trino "config.properties" | default dict }}
{{- $authen := .Values.authen }}

{{- $_ := unset $config "coordinator" }}
{{- $_ := unset $config "node-scheduler.include-coordinator" }}
{{- $_ := unset $config "discovery-server.enabled" }}
{{- $_ := unset $config "discovery.uri" }}

{{- $httpServer := .Values.httpServer }}
{{- $_ := set $config "http-server.http.enabled"  $httpServer.http.enabled  }}
{{- $_ := set $config "http-server.http.port"     $httpServer.http.port  }}
{{- if $httpServer.https.enabled }}
  {{- $_ := set $config "http-server.https.enabled" $httpServer.https.enabled }}
  {{- $_ := set $config "http-server.https.port"    $httpServer.https.port }}
  {{- $_ := set $config "http-server.https.keystore.path"   $httpServer.keystore.path }}
  {{- $_ := set $config "http-server.https.keystore.key"    $httpServer.keystore.key  }}
  {{- $_ := set $config "http-server.https.truststore.path" $httpServer.truststore.path }}
  {{- $_ := set $config "http-server.https.truststore.key"  $httpServer.truststore.key  }}
{{- end }}

{{- $coordinatorConfig := deepCopy $config }}
{{- $workerConfig := deepCopy $config }}

{{- if $authen.type }}
  {{- $authenType := lower $authen.type }}
  {{- $_ := set $coordinatorConfig "web-ui.authentication.type" $authenType }}
  {{- $_ := set $coordinatorConfig "http-server.authentication.type" $authenType }}
  {{- $sharedSecret := required "sharedSecret is required when authentication is enabled" $authen.sharedSecret }}
  {{- $_ := set $coordinatorConfig "internal-communication.shared-secret" $sharedSecret }}
  {{- $_ := set $workerConfig      "internal-communication.shared-secret" $sharedSecret }}

  {{- if eq $authenType "oauth2" }}
    {{- range $key, $value := $authen.oauth2 }}
      {{- $_ := set $coordinatorConfig (printf "http-server.authentication.oauth2.%s" $key) $value }}
    {{- end }}
  {{- end }}

  ## TODO: Support password authentication
  # {{- if eq $authenType "password" }}
  # {{- end }}

  {{- if eq $authenType "kerberos" }}
    {{- range $key, $value := $authen.kerberos }}
      {{- $_ := set $coordinatorConfig (printf "http-server.authentication.krb5.%s" $key) $value }}
    {{- end }}
  {{- end }}

{{- end }}

{{- $_ := include "dict-cleanup" $coordinatorConfig }}
{{- $_ := include "dict-cleanup" $workerConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trino.fullname" . }}-config
  labels:
    {{- include "trino.labels" . | nindent 4 }}
data:
  coordinator-config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=false
    discovery.uri={{ printf "http://%s-discovery:8080" (include "trino.fullname" .) }}
    {{- range $key, $value := $coordinatorConfig }}
    {{ $key }}={{ $value }}
    {{- end }}

  worker-config.properties: |
    coordinator=false
    discovery.uri={{ printf "http://%s-discovery:8080" (include "trino.fullname" .) }}
    {{- range $key, $value := $workerConfig }}
    {{ $key }}={{ $value }}
    {{- end }}
