{{- $trino := .Values.trino }}
{{- $config := index $trino "config.properties" | default dict }}

{{- $_ := unset $config "coordinator" }}
{{- $_ := unset $config "node-scheduler.include-coordinator" }}
{{- $_ := unset $config "discovery-server.enabled" }}
{{- $_ := unset $config "discovery.uri" }}

{{- $httpServer := .Values.httpServer }}
{{- $_ := set $config "http-server.http.enabled"  $httpServer.http.enabled  }}
{{- $_ := set $config "http-server.http.port"     $httpServer.http.port  }}
{{- $_ := set $config "http-server.https.enabled" $httpServer.https.enabled }}
{{- $_ := set $config "http-server.https.port"    $httpServer.https.port }}
{{- $_ := set $config "http-server.https.keystore.path"   $httpServer.keystore.path }}
{{- $_ := set $config "http-server.https.keystore.key"    $httpServer.keystore.key  }}
{{- $_ := set $config "http-server.https.truststore.path" $httpServer.truststore.path }}
{{- $_ := set $config "http-server.https.truststore.key"  $httpServer.truststore.key  }}

{{- $coordinatorConfig := deepCopy $config }}
{{- $workerConfig := deepCopy $config }}

{{- $authen := .Values.authen }}
{{- if eq $authen.type "oauth2" }}
  {{- $_ := set $coordinatorConfig "web-ui.authentication.type" "oauth2" }}
  {{- $_ := set $coordinatorConfig "http-server.authentication.type" "oauth2" }}
  {{- $_ := set $coordinatorConfig "http-server.authentication.oauth2.auth-url" $authen.oauth2.authUrl }}
  {{- $_ := set $coordinatorConfig "http-server.authentication.oauth2.jwks-url" $authen.oauth2.jwksUrl }}
  {{- $_ := set $coordinatorConfig "http-server.authentication.oauth2.token-url" $authen.oauth2.tokenUrl }}
  {{- $_ := set $coordinatorConfig "http-server.authentication.oauth2.client-id" $authen.oauth2.clientId }}
  {{- $_ := set $coordinatorConfig "http-server.authentication.oauth2.client-secret" $authen.oauth2.clientSecret }}
  {{- $_ := set $coordinatorConfig "http-server.authentication.oauth2.principal-field" $authen.oauth2.principalField }}
{{- end }}
{{- $_ := include "dict-cleanup" $coordinatorConfig }}
{{- $_ := include "dict-cleanup" $workerConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trino.fullname" . }}-config
  labels:
    {{- include "trino.labels" . | nindent 4 }}
data:
  coordinator-config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=false
    discovery-server.enabled=true
    discovery.uri={{ printf "http://%s:8080" (include "trino.fullname" .) }}
    {{- range $key, $value := $coordinatorConfig }}
    {{ $key }}={{ $value }}
    {{- end }}

  worker-config.properties: |
    coordinator=false
    discovery.uri={{ printf "http://%s:8080" (include "trino.fullname" .) }}
    {{- range $key, $value := $workerConfig }}
    {{ $key }}={{ $value }}
    {{- end }}
