elasticsearch:
  host: localhost

ebean:
  type: mysql
  host: mysql.local
  port: 3306
  database: datahub
  username: user
  password: pass

kafka:
  bootstrapServers: [bootstrap.kafa:9092]
  confluent:
    url: http://localhost:1234

##############################
actions:
  pipelineConfigs:
  - name: slack_action
    action:
      type: slack
      config:
        base_url: ${DATAHUB_BASE_URL}
        bot_token: DATAHUB_ACTIONS_SLACK_BOT_TOKEN
        signing_secret: DATAHUB_ACTIONS_SLACK_SIGNING_SECRET
        default_channel: DATAHUB_ACTIONS_SLACK_CHANNEL
        suppress_system_activity: true
  - name: teams_action
    action:
      type: teams
      config:
        base_url: ${DATAHUB_BASE_URL}
        webhook_url: DATAHUB_ACTIONS_TEAMS_WEBHOOK_URL
        suppress_system_activity: true

actionServiceAccount:
  name: super-actions
  clusterRole:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]

authn:
  gms:
    enabled: true
