ebean:
  type: mysql
  host: mysql.local
  port: 3306
  database: datahub
  username: user
  password: pass

kafka:
  bootstrapServers: [bootstrap.kafa:9092]
  confluent:
    url: http://localhost:1234

elasticsearch:
  host: localhost
##############################
graphService:
  impl: neo4j

neo4j:
  uri: bolt://neo4j.local
  username: neo4j
  password: abcxyz
