{{- $webserver := mergeOverwrite (deepCopy .Values.commons) .Values.webserver -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airflow.fullname" . }}-webserver
  labels:
    {{- include "airflow.webserver.labels" . | nindent 4 }}
  annotations:
    {{- toYaml $webserver.annotations | nindent 4 }}
spec:
  replicas: {{ $webserver.replicas }}
  selector:
    matchLabels:
      {{- include "airflow.webserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "airflow.webserver.selectorLabels" . | nindent 8 }}
      annotations:
        {{- with $webserver.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "airflow.checksum" . | nindent 8 }}
    spec:
    {{- with .Values.image.pullSecret }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      enableServiceLinks: false
      containers:
      {{- if and (eq .Values.dags.fetcher "git") .Values.dags.git.sidecarContainer -}}
        {{- include "airflow.gitsync" . | nindent 8 }}
      {{- end }}
        - name: webserver
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with $webserver.command }}
          command:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with $webserver.args }}
          args:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          env:
            {{- toYaml $webserver.env | nindent 12 }}
          envFrom:
            - configMapRef:
                name: "{{ template "airflow.fullname" . }}-env"
          ports:
          - name: web
            protocol: TCP
            containerPort: 8080
          volumeMounts:
            {{- include "airflow.volumeMounts" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: web
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: web
            periodSeconds: 30
          resources:
            {{- toYaml $webserver.resources | nindent 12 }}
      serviceAccountName: {{ include "airflow.serviceAccountName" . }}
      priorityClassName:  {{ $webserver.priorityClassName }}
      runtimeClassName:   {{ $webserver.runtimeClassName }}
      schedulerName:      {{ $webserver.schedulerName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- include "airflow.volumes" . | nindent 8 }}
    {{- with $webserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $webserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $webserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
