{{- $webserver := mergeOverwrite (deepCopy .Values.commons) .Values.webserver -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow.fullname" . }}-webserver
  labels:
    {{- include "airflow.webserver.labels" . | nindent 4 }}
  annotations:
    {{- toYaml $webserver.serviceAnnotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8080
    targetPort: web
    protocol: TCP
    name: web
  selector:
    {{- include "airflow.webserver.selectorLabels" . | nindent 4 }}
