nameOverride: ""
fullnameOverride: ""

image:
  repository: confluentinc/cp-kafka-rest
  tag: 6.1.0

imagePullPolicy: IfNotPresent
imagePullSecrets: []
# - name: regcred

# https://docs.confluent.io/platform/current/kafka-rest/production-deployment/rest-proxy/config.html
restProxy:
  bootstrap.servers: ""
  schema.registry.url: ""

replicas: 1

labels: {}
podLabels: {}
annotations: {}
podAnnotations: {}

command: []
args: []
env: []
volumes: []
volumeMounts: []

podSecurityContext: {}
  # fsGroup: 2000
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

schedulerName: null
runtimeClassName: null
priorityClassName: null

affinity: {}
tolerations: []
nodeSelector: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

rbac:
  # If true, create & use RBAC resources
  create: true
  # If true, create and use PodSecurityPolicy
  pspEnable: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podDisruptionBudget:
  enabled: false
  # minAvailable: 1
  # maxUnavailable:

service:
  type: ClusterIP
  port: 8082
  nodePort:
  annotations: {}
  sessionAffinity: None
  sessionAffinityConfig: {}

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: rest-proxy.local
      paths: []
  tls: []
  #  - secretName: rest-proxy-tls
  #    hosts:
  #      - rest-proxy.local

logging:
  root: INFO
  loggers: {}
    # kafka.controller: WARN
    # kafka.foo.bar: DEBUG

metrics:
  enabled: false
  podMonitor:
    enabled: false
