{{- $worker := mergeOverwrite (deepCopy .Values.commons) .Values.worker -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow.fullname" . }}-worker
  labels:
    {{- include "airflow.worker.labels" . | nindent 4 }}
  annotations:
    {{- toYaml $worker.serviceAnnotations | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8793
    name: worker-log
    protocol: TCP
    targetPort: worker-log
  selector:
    {{- include "airflow.worker.selectorLabels" . | nindent 4 }}
