{{- $worker := mergeOverwrite (deepCopy .Values.commons) .Values.worker -}}
{{- if eq (include "airflow.normalizeExecutor" .) "CeleryExecutor" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "airflow.fullname" . }}-worker
  labels:
    {{- include "airflow.worker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8793
      name: worker
      protocol: TCP
      targetPort: worker
  selector:
    {{- include "airflow.worker.selectorLabels" . | nindent 4 }}
{{- end }}
