{{- $worker := mergeOverwrite (deepCopy .Values.commons) .Values.worker -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "airflow.fullname" . }}-worker
  labels:
    {{- include "airflow.worker.labels" . | nindent 4 }}
    {{- with $worker.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml $worker.annotations | nindent 4 }}
spec:
  replicas: {{ $worker.replicas }}
  serviceName: "{{ template "airflow.fullname" . }}-worker"
  podManagementPolicy: Parallel
  updateStrategy:
    ## Kill the workers as soon as possible, the scheduler will restart the failed jobs later
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "airflow.worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "airflow.worker.selectorLabels" . | nindent 8 }}
        {{- with $worker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- include "airflow.checksum" . | nindent 8 }}
        {{- with $worker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      enableServiceLinks: false
      terminationGracePeriodSeconds: {{ $worker.terminationPeriod }}
      containers:
      {{- if eq .Values.dags.fetcher "git" }}
        {{- include "airflow.gitsync.sidecar" . | nindent 8 }}
      {{- end }}
        - name: worker
          image: "{{ $worker.image.repository }}:{{ $worker.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{- with $worker.command }}
          command:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with $worker.args }}
          args:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          env:
            {{- toYaml $worker.env | nindent 12 }}
          envFrom:
            - configMapRef:
                name: "{{ template "airflow.fullname" . }}-env"
          ports:
            - name: worker
              protocol: TCP
              containerPort: 8793
          volumeMounts:
            {{- include "airflow.volumeMounts" . | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: worker
            periodSeconds: 30
          resources:
            {{- toYaml $worker.resources | nindent 12 }}
          {{- if eq .Values.dags.fetcher "git" }}
          lifecycle:
            postStart:
              exec:
                command:
                  - bash
                  - -c
                  - |
                    {{- include "airflow.gitsync.postStart" . | nindent 20 }}
          {{- end }}
      serviceAccountName: {{ include "airflow.serviceAccountName" . }}
      priorityClassName:  {{ $worker.priorityClassName }}
      runtimeClassName:   {{ $worker.runtimeClassName }}
      schedulerName:      {{ $worker.schedulerName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- include "airflow.volumes" . | nindent 8 }}
    {{- with $worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
