apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "schema-registry.fullname" . }}
  labels:
    {{- include "schema-registry.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.schemaRegistry }}
  {{- $key = $key | replace "_" "___" }}
  {{- $key = $key | replace "-" "__" }}
  {{- $key = $key | replace "." "_" }}
  SCHEMA_REGISTRY_{{ $key | upper }}: {{ $value | quote }}
  {{- end }}

  SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: {{ .Values.logging.root }}
  {{- with .Values.logging.loggers }}
  {{- $loggers := list -}}
  {{- range $key, $value := . }}
    {{- $loggers = append $loggers (printf "%s=%s" $key $value) -}}
  {{- end }}
  SCHEMA_REGISTRY_LOG4J_LOGGERS: {{ $loggers | join "," | quote }}
  {{- end }}
