apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "schema-registry.fullname" . }}
  labels:
    {{- include "schema-registry.labels" . | nindent 4 }}
{{- with .Values.schemaRegistry }}
data:
  {{- range $key, $value := . }}
  SCHEMA_REGISTRY_{{ $key | replace "." "_" | upper }}: {{ $value | quote }}
  {{- end }}
{{- end }}
