apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "schema-registry.fullname" . }}
  labels:
    {{- include "schema-registry.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  serviceName: {{ include "schema-registry.fullname" . }}
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "schema-registry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "schema-registry.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- include "schema-registry.checksum" . | nindent 8 }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if and .Values.metrics.enabled (not .Values.metrics.podMonitor.enabled) }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "9404"
        prometheus.io/path: "/"
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableServiceLinks: false
      {{- if .Values.metrics.enabled }}
      initContainers:
        - name: jmx
          image: bitnami/jmx-exporter:0.15.0
          command:
            - cp
            - /opt/bitnami/jmx-exporter/jmx_prometheus_javaagent.jar
            - /tmp/jmx-exporter/
          volumeMounts:
            - name: jmx-exporter
              mountPath: /tmp/jmx-exporter/
      {{- end }}
      containers:
        - name: schema-registry
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          {{- if .Values.metrics.enabled }}
            - name: SCHEMA_REGISTRY_JMX_OPTS
              value: -javaagent:/tmp/jmx-exporter/jmx_prometheus_javaagent.jar=9404:/tmp/jmx-config/schema-registry-metrics.yaml
          {{- end }}
          {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "schema-registry.fullname" . }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: 9404
              protocol: TCP
          {{- end }}
          volumeMounts:
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.metrics.enabled }}
            - name: jmx-exporter
              mountPath: /tmp/jmx-exporter/
            - name: jmx-config
              mountPath: /tmp/jmx-config/
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /v1/metadata/id
              port: http
            initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      serviceAccountName: {{ include "schema-registry.serviceAccountName" . }}
      priorityClassName:  {{ .Values.priorityClassName }}
      runtimeClassName:   {{ .Values.runtimeClassName }}
      schedulerName:      {{ .Values.schedulerName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.metrics.enabled }}
        - name: jmx-exporter
          emptyDir: {}
        - name: jmx-config
          configMap:
            name: {{ include "schema-registry.fullname" . }}-metrics
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
