{{- if and .Values.serviceAccount.create .Values.router.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "druid.router.serviceAccountName" . }}
  labels:
    {{- include "druid.router.labels" . | nindent 4 }}
{{- end }}
