# See:
# * https://grafana.com/docs/loki/latest/reference/api/
# * https://github.com/bitnami/charts/blob/main/bitnami/grafana-loki/templates/gateway/configmap-http.yaml
# * https://github.com/grafana/loki/blob/v2.9.2/production/helm/loki/templates/_helpers.tpl#L560-L773
# Access Logs:
# * https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage
# * https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/open_telemetry/v3/logs_service.proto
# * https://github.com/helpfulBadger/envoy_getting_started/blob/master/08_log_taps_traces/front-envoy-jaeger.yaml
{{- $accessLog := .Values.proxy.accessLog }}
---
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 8001
static_resources:
  listeners:
    - name: loki
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 3100
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            path: /
                          direct_response:
                            status: 200
                            body:
                              inline_string: OK
                        # Distributor
                        - match:
                            path: /api/prom/push  # Deprecated, use /loki/api/v1/push instead
                          route:
                            cluster: loki-write-http
                        - match:
                            path: /loki/api/v1/push
                          route:
                            cluster: loki-write-http
                        # Ruler
                        - match:
                            prefix: /api/prom/rules
                          route:
                            cluster: loki-backend-http
                        - match:
                            prefix: /loki/api/v1/rules
                          route:
                            cluster: loki-backend-http
                        - match:
                            path: /prometheus/api/v1/alerts
                          route:
                            cluster: loki-backend-http
                        - match:
                            path: /prometheus/api/v1/rules
                          route:
                            cluster: loki-backend-http
                        # Compactor
                        - match:
                            path: /loki/api/v1/delete
                          route:
                            cluster: loki-backend-http
                        # QueryFrontend, Querier
                        - match:
                            path: /api/prom/tail  # Deprecated, use /loki/api/v1/tail instead
                          route:
                            cluster: loki-read-http
                        - match:
                            path: /loki/api/v1/tail
                          route:
                            cluster: loki-read-http
                        - match:
                            prefix: /api/prom
                          route:
                            cluster: loki-read-http
                        - match:
                            prefix: /loki/api/v1
                          route:
                            cluster: loki-read-http
                access_log:
                {{- if $accessLog.openTelemetry.enabled }}
                  {{- $ot := $accessLog.openTelemetry }}
                  - name: envoy.access_loggers.open_telemetry
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.open_telemetry.v3.OpenTelemetryAccessLogConfig
                      common_config:
                        log_name: loki
                        transport_api_version: V3
                        grpc_service:
                          {{- toYaml $ot.grpcService | nindent 26 }}
                      body:
                        # default log format (https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#default-format-string)
                        string_value: >
                          [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%"
                      attributes:
                        {{- .Files.Get "files/opentelemetry-attributes.yaml" | trim | nindent 24 }}
                {{- end }}
  clusters:
    - name: loki-read-http
      type: LOGICAL_DNS
      lb_policy: round_robin
      load_assignment:
        cluster_name: loki-read-http
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: {{ include "loki.fullname" . }}-read
                      port_value: 3100
    - name: loki-write-http
      type: LOGICAL_DNS
      lb_policy: round_robin
      load_assignment:
        cluster_name: loki-write-http
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: {{ include "loki.fullname" . }}-write
                      port_value: 3100
    - name: loki-backend-http
      type: LOGICAL_DNS
      lb_policy: round_robin
      load_assignment:
        cluster_name: loki-backend-http
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: {{ include "loki.fullname" . }}-backend
                      port_value: 3100
