replicaCount: 2

secret:
  create: false

ingress:
  enabled: false
  # className: ""
  # annotations: {}
  #   # kubernetes.io/ingress.class: nginx
  #   # kubernetes.io/tls-acme: "true"
  # hosts:
  #   - host: kafka.dungdm93.local
  #     paths:
  #       - path: /
  #         pathType: Prefix
  # tls: []
  #   # - secretName: kafka.dungdm93.local-tls
  #   #   hosts:
  #   #     - kafka.dungdm93.local

resources:
  requests:
    cpu: 128m
    memory: 128Mi
  limits:
    cpu: 2000m
    memory: 2Gi

autoscaling:
  enabled: false

console:
  config:
    kafka:
      clientId: redpanda-console
      brokers:
        - databus-kafka-bootstrap:9092
      schemaRegistry:
        enabled: true
        urls:
          - http://schema-registry:8081

    connect:
      enabled: true
      clusters:
        - name: debezium
          url: http://debezium-connect-api:8083

    logger:
      level: info
