apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: debezium
  namespace: kafka
  annotations:
   strimzi.io/use-connector-resources: "true"
spec:
  version: 3.4.0
  replicas: 3
  bootstrapServers: databus-kafka-bootstrap:9092
  image: ghcr.io/dungdm93/docker/kafka-debezium:2.1.3-kafka-3.4.0
  config:
    group.id: kafka.connect.debezium
    config.storage.topic: _debezium.configs
    offset.storage.topic: _debezium.offsets
    status.storage.topic: _debezium.status
    key.converter:    io.confluent.connect.avro.AvroConverter
    value.converter:  io.confluent.connect.avro.AvroConverter
    key.converter.schema.registry.url:    http://schema-registry.kafka.svc:8081
    value.converter.schema.registry.url:  http://schema-registry.kafka.svc:8081
  resources:
    requests:
      cpu: "4"
      memory: 8Gi
    limits:
      cpu: "12"
      memory: 24Gi
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: kafka-metrics
        key: kafka-connect-metrics.yaml
