repositories:
- name: prometheus-community
  url:  https://prometheus-community.github.io/helm-charts

releases:
- name: node-exporter
  namespace: grafana-agent
  chart: prometheus-community/prometheus-node-exporter
  version: 4.8.1
  values:
  - ./node-exporter.yaml
  - fullnameOverride: node-exporter
