{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "superset.beat.serviceAccountName" . }}
  labels:
    {{- include "superset.beat.labels" . | nindent 4 }}
{{- end }}
