version: "3.7"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0
    command: [start-dev]
    environment:
      # https://www.keycloak.org/server/all-config
      # KC_DB:               postgres
      # KC_DB_URL_HOST:      database
      # KC_DB_URL_PORT:      5432
      # KC_DB_URL_DATABASE:  keycloak
      # KC_DB_USERNAME:      keycloak
      # KC_DB_PASSWORD:      password

      KEYCLOAK_ADMIN:           admin
      KEYCLOAK_ADMIN_PASSWORD:  SuperSecr3t
    ports:
    - 8080:8080
    volumes:
    - keycloak_data:/opt/keycloak/data

volumes:
  keycloak_data:

networks:
  default:
    name: cogwheel
