version: "3.7"

services:
  minio:
    image: minio/minio
    command: [server, /data]
    environment:
      MINIO_ROOT_USER: admin            # MINIO_ACCESS_KEY
      MINIO_ROOT_PASSWORD: SuperSecr3t  # MINIO_SECRET_KEY
      MINIO_ADDRESS: :9000
      MINIO_CONSOLE_ADDRESS: :9001
    network_mode: host
    volumes:
    - minio_data:/data

volumes:
  minio_data:

networks:
  default:
    name: cogwheel
