version: "3.7"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: SuperSecr3t
    ports:
    - 5432:5432
    volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  default:
    name: cogwheel
