version: "3.7"

services:
  vault:
    image: vault:1.12.1
    environment:
      VAULT_ADDR: http://localhost:8200
      VAULT_DEV_ROOT_TOKEN_ID: SuperSecr3t
    ports:
    - 8200:8200
    cap_add:
    - IPC_LOCK
    volumes:
    - ./config/vault:/vault/config
    - vault_data:/vault/file

volumes:
  vault_data:

networks:
  default:
    name: cogwheel
