---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: l2
  namespace: metallb-system
spec:
  addresses:
    - 192.168.11.0/24
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - l2
