nameOverride: tivan

trackOffsets: true
input:
  systemd:
    enabled: true

filter:
  mergeJSONLog: true
  mergeLogKey:  payload

# Sine FluentBit is NOT official support loki yet
backend:
  type: loki

# docs: https://github.com/grafana/loki/blob/v1.1.0/cmd/fluent-bit/README.md
extraEntries:
  input: |-
    DB              /tail-db/systemd-services-state.db
  output: |-
    [Output]
      Name          loki
      Match         *
      Url           http://loki.kube-observability:3100/loki/api/v1/push
      Labels        '{job="fluent-bit"}'
      RemoveKeys    'kubernetes,stream'
      LabelMapPath  /fluent-bit/etc/labelmap.json
      LineFormat    json
      LogLevel      warn

extraVolumes:
- name: loki-labelmap
  configMap:
    name: loki-labelmap
extraVolumeMounts:
- name: loki-labelmap
  mountPath: /fluent-bit/etc/labelmap.json
  subPath: labelmap.json

rbac:
  create: true
  pspEnabled: true
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
priorityClassName: addons-critical
