{{- $worker := mergeOverwrite (deepCopy .Values.commons) .Values.worker -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "superset.fullname" . }}-worker
  labels:
    {{- include "superset.worker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "superset.worker.selectorLabels" . | nindent 4 }}
