{{- if and .Values.serviceAccount.create .Values.overlord.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "druid.overlord.serviceAccountName" . }}
  labels:
    {{- include "druid.overlord.labels" . | nindent 4 }}
{{- end }}
