{{- if .Values.overlord.enabled }}
{{- $overlord := mergeOverwrite (deepCopy .Values.commons) .Values.overlord -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "druid.fullname" . }}-overlord
  labels:
    {{- include "druid.overlord.labels" . | nindent 4 }}
    {{- with $overlord.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml $overlord.annotations | nindent 4 }}
spec:
  replicas: {{ $overlord.replicas }}
  serviceName: {{ template "druid.fullname" . }}-overlord
  selector:
    matchLabels:
      {{- include "druid.overlord.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "druid.overlord.selectorLabels" . | nindent 8 }}
        {{- with $overlord.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- include "druid.overlord.checksum" . | nindent 8 }}
        {{- with $overlord.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      enableServiceLinks: false
      containers:
        - name: druid-overlord
          image: {{ include "druid.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with $overlord.command }}
          command:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with $overlord.args }}
          args:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          env:
            {{- toYaml $overlord.env | nindent 12 }}
          ports:
            - name: http
              protocol: TCP
              containerPort: 8090
          {{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion }}
          startupProbe:
            httpGet:
              port: http
              path: /status/health
            periodSeconds: 10
            failureThreshold: 30  # total 5m
          {{- end }}
          livenessProbe:
            httpGet:
              port: http
              path: /status/health
          readinessProbe:
            httpGet:
              port: http
              path: /status/selfDiscovered
          volumeMounts:
            {{- include "druid.overlord.volumeMounts" . | nindent 12 }}
          resources:
            {{- toYaml $overlord.resources | nindent 12 }}
          securityContext:
            {{- toYaml $overlord.securityContext | nindent 12 }}
      serviceAccountName: {{ include "druid.overlord.serviceAccountName" . }}
      priorityClassName:  {{ $overlord.priorityClassName }}
      runtimeClassName:   {{ $overlord.runtimeClassName }}
      schedulerName:      {{ $overlord.schedulerName }}
      securityContext:
        {{- toYaml $overlord.podSecurityContext | nindent 8 }}
      volumes:
        {{- include "druid.overlord.volumes" . | nindent 8 }}
    {{- with $overlord.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $overlord.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $overlord.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
