{{- $runtime := index .Values.druid.coordinator "runtime.properties" | default dict }}
{{- $jvm := index .Values.druid.coordinator "jvm.config" | default "" }}
{{- $extraJvm := index .Values.druid.coordinator "extra.jvm.config" | default "" }}
{{- $config := omit .Values.druid.coordinator "runtime.properties" "jvm.config" "extra.jvm.config" }}

{{- if not .Values.overlord.enabled }}
{{- $_ := set $runtime "druid.coordinator.asOverlord.enabled" true }}
{{- $_ := set $runtime "druid.coordinator.asOverlord.overlordService" "druid/overlord" }}

{{- $overlordRuntime := index .Values.druid.overlord "runtime.properties" | default dict }}
{{- $runtime = mergeOverwrite $overlordRuntime $runtime }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "druid.fullname" . }}-coordinator
  labels:
    {{- include "druid.coordinator.labels" . | nindent 4 }}
data:
  runtime.properties: |
    {{- range $key, $value := $runtime }}
    {{ $key }}={{ has (kindOf $value) (list "map" "slice") | ternary (mustToJson $value) $value }}
    {{- end }}

  jvm.config: |
    {{ $jvm | nindent 4 | trim }}
    {{- if $extraJvm }}
    {{ $extraJvm | nindent 4 | trim }}
    {{- end }}

  {{- range $file, $content := $config }}
  {{ $file }}: |
    {{ $content | nindent 4 | trim }}
  {{- end }}
