repositories:
- name: cert-manager
  url:  https://charts.jetstack.io

releases:
- name: cert-manager
  namespace: cert-manager
  chart: cert-manager/cert-manager
  version: 1.12.1
  values:
  - ./cert-manager.yaml
  - fullnameOverride: cert-manager
