{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rest-proxy.fullname" . }}-metrics
  labels:
    {{- include "rest-proxy.labels" . | nindent 4 }}
data:
  rest-proxy-metrics.yaml: |
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    rules:
    - pattern: kafka.rest<type=jetty-metrics><>connections-active
      name: kafka_rest_connections_active
      help: Total number of active Jetty TCP connections
      type: GAUGE
    - pattern: kafka.rest<type=jetty-metrics><>connections-(?<kind>opened|closed)-rate
      name: kafka_rest_connections_rate
      help: The average rate per second of opened/closed TCP connections
      type: GAUGE
      labels:
        kind: ${kind}
    # (request|response)-(rate|byte-rate|size-*)
    - pattern: kafka.rest<type=jersey-metrics><>(?<endpoint>.+).(?<kind>request|response)-rate
      name: kafka_rest_${kind}_rate
      help: The average number of HTTP ${kind} per second
      type: GAUGE
      labels:
        endpoint: ${endpoint}
    - pattern: kafka.rest<type=jersey-metrics><>(?<kind>request|response)-rate
      name: kafka_rest_${kind}_rate
      help: The average number of HTTP ${kind} per second
      type: GAUGE
      labels:
        endpoint: "*"
    - pattern: kafka.rest<type=jersey-metrics><>(?<endpoint>.+).(?<kind>request|response)-byte-rate
      name: kafka_rest_${kind}_byte_rate
      help: Bytes/second of incoming requests/outgoing responses
      type: GAUGE
      labels:
        endpoint: ${endpoint}
    - pattern: kafka.rest<type=jersey-metrics><>(?<kind>request|response)-byte-rate
      name: kafka_rest_${kind}_byte_rate
      help: Bytes/second of incoming requests/outgoing responses
      type: GAUGE
      labels:
        endpoint: "*"
    - pattern: kafka.rest<type=jersey-metrics><>(?<endpoint>.+).(?<kind>request|response)-size-(?<agg>avg|max)
      name: kafka_rest_${kind}_size_${agg}
      help: The ${agg} ${kind} size in bytes
      type: GAUGE
      labels:
        endpoint: ${endpoint}
    - pattern: kafka.rest<type=jersey-metrics><>(?<kind>request|response)-size-(?<agg>avg|max)
      name: kafka_rest_${kind}_size_${agg}
      help: The ${agg} ${kind} size in bytes
      type: GAUGE
      labels:
        endpoint: "*"
    # request_duration
    - pattern: kafka.rest<type=jersey-metrics><>(?<endpoint>.+).request-latency-(?<percentile>\d+)
      name: kafka_rest_request_duration
      help: The summary metrics of request duration in ms
      type: GAUGE
      labels:
        endpoint: ${endpoint}
        quantile: 0.${percentile}
    - pattern: kafka.rest<type=jersey-metrics><>(?<endpoint>.+).request-latency-(?<agg>avg|max)
      name: kafka_rest_request_duration_${agg}
      help: The ${agg} request latency in ms
      type: GAUGE
      labels:
        endpoint: ${endpoint}
    - pattern: kafka.rest<type=jersey-metrics><>request-latency-(?<percentile>\d+)
      name: kafka_rest_request_duration
      help: The summary metrics of request duration in ms
      type: GAUGE
      labels:
        endpoint: "*"
        quantile: 0.${percentile}
    - pattern: kafka.rest<type=jersey-metrics><>request-latency-(?<agg>avg|max)
      name: kafka_rest_request_duration_${agg}
      help: The ${agg} request latency in ms
      type: GAUGE
      labels:
        endpoint: "*"
    # request_status_rate
    - pattern: kafka.rest<type=jersey-metrics><>request-error-rate
      name: kafka_rest_request_status_rate
      help: The average number of requests per second that resulted in HTTP responses
      type: GAUGE
      labels:
        endpoint: "*"
        http_code: "*"
    - pattern: kafka.rest<type=jersey-metrics><>(?<endpoint>.+).request-error-rate
      name: kafka_rest_request_status_rate
      help: The average number of requests per second that resulted in HTTP responses
      type: GAUGE
      labels:
        endpoint: ${endpoint}
        http_code: "*"
    - pattern: kafka.rest<type=jersey-metrics, http_status_code=(?<code>.+)><>request-error-rate
      name: kafka_rest_request_status_rate
      help: The average number of requests per second that resulted in HTTP responses
      type: GAUGE
      labels:
        endpoint: "*"
        http_code: ${code}
    - pattern: kafka.rest<type=jersey-metrics, http_status_code=(?<code>.+)><>(?<endpoint>.+).request-error-rate
      name: kafka_rest_request_status_rate
      help: The average number of requests per second that resulted in HTTP responses
      type: GAUGE
      labels:
        endpoint: ${endpoint}
        http_code: ${code}
{{- end }}
