{{- if .Values.rbac.pspEnable }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "rest-proxy.fullname" . }}
  labels:
    {{- include "rest-proxy.labels" . | nindent 4 }}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default,runtime/default
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  runtime/default
    apparmor.security.beta.kubernetes.io/defaultProfileName:  runtime/default
spec:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  volumes:
    - emptyDir
    - configMap
    - secret
    - projected
    - downwardAPI
    - persistentVolumeClaim
  hostNetwork: false
  hostIPC: false
  hostPID: false
  seLinux:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  runAsGroup:
    rule: MustRunAs
    ranges: # Forbid root
      - min: 1
        max: 65535
  supplementalGroups:
    rule: MustRunAs
    ranges: # Forbid root
      - min: 1
        max: 65535
  fsGroup:
    rule: MustRunAs
    ranges: # Forbid root
      - min: 1
        max: 65535
{{- end }}
