{{- $config := deepCopy .Values.config }}
{{- $common := (dict "common" dict | mergeOverwrite $config).common }}

{{- $ringKVStore := deepCopy .Values.ringKVStore }}
{{- if eq $ringKVStore.store "memberlist" }}
  {{- $memberlist := $ringKVStore.memberlist }}
  {{- $members := list (printf "dnssrv+%s-memberlist:%d" (include "loki.fullname" .) (int $memberlist.bind_port)) }}
  {{- $_ := set $memberlist "join_members" $members }}

  {{- $_ := dict "memberlist" $memberlist | mergeOverwrite $config -}}
{{- end }}
{{- $_ := unset $ringKVStore "memberlist" }}
{{- $_ := dict "ring" (dict "kvstore" $ringKVStore) | mergeOverwrite $common -}}

{{- $_ := dict "storage" .Values.storage | mergeOverwrite $common -}}
{{- $compactorAddress := include "loki.fullname" . -}}
{{- if eq (lower .Values.deploymentMode) "simplescalable" }}
  {{- $compactorAddress = printf "%s-backend" $compactorAddress }}
{{- end }}
{{- $_ := set $common "compactor_address" $compactorAddress }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.fullname" . }}-config
  labels:
    {{- include "loki.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml $config | nindent 4 }}
