{{- range .Values.nodeGroups }}
{{- $nodeGroup := mergeOverwrite (deepCopy $.Values.commons) . -}}
{{- if and $nodeGroup.podDisruptionBudget.enabled (gt (int $nodeGroup.replicas | default 1) 1) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "opensearch.fullname" $ }}-{{ $nodeGroup.name }}
  labels:
    {{- include "opensearch.labels" $ | nindent 4 }}
    opensearch.org/node-group: {{ $nodeGroup.name }}
spec:
  selector:
    matchLabels:
      {{- include "opensearch.selectorLabels" $ | nindent 6 }}
      opensearch.org/node-group: {{ $nodeGroup.name }}
  {{- if $nodeGroup.podDisruptionBudget.minAvailable }}
  minAvailable: {{ $nodeGroup.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if $nodeGroup.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ $nodeGroup.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
{{ end }}
