---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opensearch.fullname" . }}-discovery
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "opensearch.selectorLabels" . | nindent 4 }}
  ports:
    - name: transport
      port: 9300
      targetPort: transport
      protocol: TCP
