apiVersion: v1
kind: Service
metadata:
  name: {{ include "hdfs.fullname" . }}-datanode
  labels:
    {{- include "hdfs.datanode.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 9864
    targetPort: http
    protocol: TCP
  - name: ipc
    port: 9867
    targetPort: ipc
    protocol: TCP
  selector:
    {{- include "hdfs.datanode.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: true
