druid:
  common:
    common.runtime.properties:
      first: string
      second: 10
      third: false
      empty: null
      list: [1, 2, foo, bar]
      map:
        abc: xyz
        foo: bar

  coordinator:
    extra.jvm.config: |
      -Xmx512M
      -Xms512M

    runtime.properties:
      first: string
      second: 10
      third: false
      empty: null
      list: [1, 2, foo, bar]
      map:
        abc: xyz
        foo: bar

  overlord:
    extra.jvm.config: |
      -Foobar
      -overlord

    runtime.properties:
      first: string
      second: 10
      third: false
      empty: null
      list: [1, 2, foo, bar]
      map:
        abc: xyz
        foo: bar

  router:
    extra.jvm.config: |
      -Foobar
      -router

    runtime.properties:
      first: string
      second: 10
      third: false
      empty: null
      list: [1, 2, foo, bar]
      map:
        abc: xyz
        foo: bar

  broker:
    extra.jvm.config: |
      -Foobar
      -Abcxyz

    runtime.properties:
      first: string
      second: 10
      third: false
      empty: null
      list: [1, 2, foo, bar]
      map:
        abc: xyz
        foo: bar

  middleManager:
    extra.jvm.config: |
      -Foobar
      -middleManager

    runtime.properties:
      first: string
      second: 10
      third: false
      empty: null
      list: [1, 2, foo, bar]
      map:
        abc: xyz
        foo: bar

  historical:
  - tier: default
    extra.jvm.config: |
      -Foobar
      -historical.default

    runtime.properties:
      first: string
      second: 10
      third: false
      empty: null
      list: [1, 2, foo, bar]
      map:
        abc: xyz
        foo: bar
