apiVersion: v2
name: airflow
description: Airflow helm chart
icon: https://airflow.apache.org/docs/stable/_images/pin_large.png
type: application
version: 0.7.1
appVersion: 2.0.0
# kubeVersion: ^1.15
dependencies:
- name: postgresql
  version: 10.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 12.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
maintainers:
- name: Teko's DataOps team
  email: dataops@teko.vn
