apiVersion: v2
name: airflow
description: A Helm chart for Kubernetes
icon: https://airflow.apache.org/docs/stable/_images/pin_large.png
type: application
version: 0.1.0
appVersion: 1.10.7
# kubeVersion: ^1.15
dependencies:
- name: postgresql
  version: 8.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 10.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
maintainers:
- name: Teko's DataOps team
  email: dataops@teko.vn
