apiVersion: v2
name: airflow
description: Airflow helm chart
icon: https://airflow.apache.org/docs/stable/_images/pin_large.png
type: application
version: 1.1.0
appVersion: 2.6.2
# kubeVersion: ^1.19
dependencies:
- name: postgresql
  version: 11.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 17.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
maintainers:
- name: Teko's DataOps team
  email: dataops@teko.vn
