{{- $hdfsSite := index .Values.hadoopConfig "hdfs-site.xml" }}

{{- if .Values.filesystem.s3a.enabled }}
  {{- $s3a  := .Values.filesystem.s3a }}
  {{- $conf := include "hive-metastore.filesystem.s3a" (list "global" $s3a) | fromYaml }}
  {{- $_ := mergeOverwrite $hdfsSite $conf }}

  {{- range $bucketName, $bucketAttr := $s3a.buckets }}
    {{- $conf := include "hive-metastore.filesystem.s3a" (list $bucketName $bucketAttr) | fromYaml }}
    {{- $_ := mergeOverwrite $hdfsSite $conf }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hive-metastore.fullname" . }}-hadoop-config
  labels:
    {{- include "hive-metastore.labels" . | nindent 4 }}
data:
  hdfs-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
    {{- range $name, $value := $hdfsSite }}
      <property>
        <name>{{ $name }}</name>
        <value>{{ $value }}</value>
      </property>
    {{ end }}
    </configuration>
