{{- $coreSite := index .Values.hadoopConfig "core-site.xml" }}

{{- if .Values.filesystem.s3a.enabled }}
  {{- $s3a   := .Values.filesystem.s3a }}
  {{- $props := include "hive-metastore.filesystem.s3a" (list "" $s3a) | fromYaml }}
  {{- $_ := mergeOverwrite $coreSite $props }}

  {{- range $bucketName, $bucketProps := $s3a.buckets }}
    {{- $props := include "hive-metastore.filesystem.s3a" (list $bucketName $bucketProps) | fromYaml }}
    {{- $_ := mergeOverwrite $coreSite $props }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hive-metastore.fullname" . }}-hadoop-config
  labels:
    {{- include "hive-metastore.labels" . | nindent 4 }}
data:
  core-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
    {{- range $name, $value := $coreSite }}
      <property>
        <name>{{ $name }}</name>
        <value>{{ $value }}</value>
      </property>
    {{ end }}
    </configuration>
