apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hdfs.fullname" . }}-scripts
  labels:
    {{- include "hdfs.labels" . | nindent 4 }}
data:
  hadoop-start.sh: |
    #!/bin/bash

    cp -v /etc/hdfs/* ${HADOOP_HOME}/etc/hadoop/

    namedir=$(${HADOOP_HOME}/bin/hdfs getconf -confKey dfs.namenode.name.dir | sed -E 's#file:(//)?##')

    function start_namenode() {
      if [ ! -d "$namedir" ] || [ -z "$(ls -A "$namedir")" ]; then
        echo "Formatting NameNode directory: $namedir"
        ${HADOOP_HOME}/bin/hdfs namenode -format -nonInteractive
      else
        echo "NameNode directory already existed"
        echo "!!! SKIP !!!"
      fi

      exec ${HADOOP_HOME}/bin/hdfs namenode
    }

    function start_checkpointnode() {
      mkdir -p $namedir
      exec ${HADOOP_HOME}/bin/hdfs namenode -checkpoint
    }

    function start_backupnode() {
      mkdir -p $namedir
      exec ${HADOOP_HOME}/bin/hdfs namenode -backup
    }

    function start_datanode() {
      exec ${HADOOP_HOME}/bin/hdfs datanode
    }

    function start_secondarynamenode() {
      exec ${HADOOP_HOME}/bin/hdfs secondarynamenode
    }

    case $1 in
      namenode)
        start_namenode
      ;;
      checkpointnode)
        start_checkpointnode
      ;;
      backupnode)
        start_backupnode
      ;;
      datanode)
        start_datanode
      ;;
      secondarynamenode)
        start_secondarynamenode
      ;;
      *)
        exec "$@"
      ;;
    esac
