---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "provisioner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ template "provisioner.chart" . }}
    app.kubernetes.io/name: {{ template "provisioner.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "provisioner.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "provisioner.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ template "provisioner.serviceAccountName" . }}
{{- if .Values.daemonset.priorityClassName }}
      priorityClassName: {{.Values.daemonset.priorityClassName}}
{{- end }}
{{- if .Values.daemonset.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.daemonset.nodeSelector | nindent 8 }}
{{- end }}
{{- if .Values.daemonset.tolerations }}
      tolerations:
        {{ toYaml .Values.daemonset.tolerations | nindent 8 }}
{{- end }}
{{- if .Values.daemonset.affinity }}
      affinity:
        {{ toYaml .Values.daemonset.affinity | nindent 8 }}
{{- end }}
      containers:
        - name: provisioner
          image: "{{ .Values.daemonset.image }}"
          {{- if .Values.daemonset.imagePullPolicy }}
          imagePullPolicy: {{ .Values.daemonset.imagePullPolicy | quote }}
          {{- end }}
          securityContext:
            privileged: true
{{- if .Values.daemonset.resources }}
          resources:
            {{ toYaml .Values.daemonset.resources | nindent 12 }}
{{- end }}
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JOB_CONTAINER_IMAGE
            value: "{{ .Values.daemonset.image }}"
          {{- if .Values.daemonset.kubeConfigEnv }}
          - name: KUBECONFIG
            value: {{.Values.daemonset.kubeConfigEnv}}
          {{- end }}
          {{- if .Values.serviceMonitor.enabled }}
          ports:
          - name: metrics
            containerPort: 8080
          {{- end }}
          volumeMounts:
            - name: provisioner-config
              mountPath: /etc/provisioner/config
              readOnly: true
            - name: provisioner-dev
              mountPath: /dev
            {{- range $classConfig := .Values.classes }}
            - name: {{ $classConfig.name }}
              mountPath: {{ $classConfig.mountDir | default $classConfig.hostDir }}
              mountPropagation: "HostToContainer"
            {{- end }}
      volumes:
        - name: provisioner-config
          configMap:
            name: {{ template "provisioner.fullname" . }}-config
        - name: provisioner-dev
          hostPath:
            path: /dev
        {{- range $classConfig := .Values.classes }}
        - name: {{ $classConfig.name }}
          hostPath:
            path: {{ $classConfig.hostDir }}
        {{- end }}
