airflow:
  ## Generate fernetKey with:
  ##    python -c "from cryptography.fernet import Fernet; FERNET_KEY = Fernet.generate_key().decode(); print(FERNET_KEY)"
  fernetKey: ""

  extraEnv:
  - name:   AIRFLOW__CORE__LOAD_EXAMPLES
    value:  "true"

workers:
  enabled: false

web:
  baseUrl: "https://airflow.kites.rocks"

ingress:
  enabled: true
  web:
    host: airflow.kites.rocks
    path: ""
    annotations:
      kubernetes.io/tls-acme: "true"
    tls:
      enabled: true
      secretName: airflow.kites.rocks-tls

serviceMonitor:
  enabled: true
