airflow:
  # TODO: ModuleNotFoundError: No module named 'kubernetes'
  executor: Kubernetes

  extraEnv:
  - name:  AIRFLOW__CORE__LOAD_EXAMPLES
    value: "true"
  - name:  AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY
    value: puckel/docker-airflow
  - name:  AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG
    value: 1.10.4
  - name:  AIRFLOW__KUBERNETES__NAMESPACE
    value: airflow
