airflow:
  executor: Celery

workers:
  enabled: true
  replicas: 3

  celery:
    # number of parallel celery tasks per worker
    instances: 1

flower:
  # BUG: urlPrefix is not working
  urlPrefix: /flower

ingress:
  flower:
    host: airflow.kites.rocks
    path: /flower
    annotations:
      kubernetes.io/tls-acme: "true"
      # kubernetes.io/ingress.class: nginx
    tls:
      enabled: true
      secretName: airflow.kites.rocks-tls

redis:
  enabled: true
