{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hive.fullname" . }}-metrics
  labels:
    {{- include "hive.metastore.labels" . | nindent 4 }}
data:
  hive-metastore-metrics.yaml: |
    lowercaseOutputName: true
    whitelistObjectNames:
    - "metrics:*"
    - "java.lang:*"
    - "java.nio:*"

    rules:
      # metrics:name=open_connections
      - pattern: 'metrics<name=open_connections><>Value: (-?\d+\.?\d*)'
        name: 'hive_metastore_open_connections'
        type: GAUGE
        value: $1
      # metrics:name=(create_total_count_dbs|delete_total_count_dbs|total_count_dbs)
      - pattern: 'metrics<name=(.+)_dbs><>(Count|Value): (-?\d+\.?\d*)'
        name: 'hive_metastore_db_$1'
        type: COUNTER
        value: $3
      # metrics:name=(create_total_count_tables|delete_total_count_tables|total_count_tables)
      - pattern: 'metrics<name=(.+)_tables><>(Count|Value): (-?\d+\.?\d*)'
        name: 'hive_metastore_tables_$1'
        type: COUNTER
        value: $3
      # metrics:name=(create_total_count_partitions|delete_total_count_partitions|total_count_partitions)
      - pattern: 'metrics<name=(.+)_partitions><>(Count|Value): (-?\d+\.?\d*)'
        name: 'hive_metastore_partitions_$1'
        type: COUNTER
        value: $3
      # metrics:name=directsql_errors
      - pattern: 'metrics<name=directsql_errors><>Count: (-?\d+\.?\d*)'
        name: 'hive_metastore_directsql_errors'
        type: GAUGE
        value: $1
      # metrics:name=(heap|non-heap|total).(committed|init|max|usage|used)
      - pattern: 'metrics<name=(heap|non-heap|total).(.+)><>(Count|Value): (-?\d+\.?\d*)'
        name: 'hive_metastore_memory_$2'
        type: GAUGE
        labels:
          area: $1
        value: $4
      # metrics:name=jvm.pause.extraSleepTime|info-threshold|warn-threshold
      - pattern: 'metrics<name=jvm.pause.(.+)><>(Count|Value): (-?\d+\.?\d*)'
        name: 'hive_metastore_jvm_pause_$1'
        type: GAUGE
        value: $3
      # metrics:name=daemon.count
      - pattern: 'metrics<name=daemon.count><>Value: (-?\d+\.?\d*)'
        name: 'hive_metastore_threads_daemon_thread_count'
        type: GAUGE
        value: $1
      # metrics:name=deadlock.count
      - pattern: 'metrics<name=deadlock.count><>Value: (-?\d+\.?\d*)'
        name: 'hive_metastore_threads_deadlock_thread_count'
        type: GAUGE
        value: $1
      # metrics:name=api_init
      # metrics:name=api_get_(all_functions|config_value|current_notificationEventId|databases|multi_table|next_notification|table_objects_by_name_req|tables_by_type)
      # metrics:name=api_set_ugi
      # metrics:name=api_shutdown
      - pattern: 'metrics<name=api_(.+)><>(.+): (.+)'
        name: 'hive_metastore_api'
        help: 'Rate Unit = events/second'
        type: GAUGE
        labels:
          type: $1
          attribute: $2
        value: $3
      # metrics:name=active_calls_get_all_functions|config_value|databases|multi_tables|tables_by_type
      - pattern: 'metrics<name=active_calls_get_(.+)><>Count: (-?\d+)'
        name: 'hive_metastore_active_calls_get'
        type: GAUGE
        labels:
          type: $1
        value: $2
      # metrics:name=pools.Code-Cache.usage
      # metrics:name=pools.Compressed-Class-Space.usage
      # metrics:name=pools.Metaspace.usage
      # metrics:name=pools.PS-Eden-Space.usage
      # metrics:name=pools.PS-Old-Gen.usage
      # metrics:name=pools.PS-Survivor-Space.usage
      # metrics:name=PS-MarkSweep.count
      # metrics:name=PS-MarkSweep.time
      # metrics:name=PS-Scavenge.count
      # metrics:name=PS-Scavenge.time
      # metrics:name=blocked.count
      # metrics:name=count
      # metrics:name=deadlocks
      # metrics:name=direct.capacity
      # metrics:name=direct.count
      # metrics:name=direct.used
      # metrics:name=loaded
      # metrics:name=mapped.capacity
      # metrics:name=mapped.count
      # metrics:name=mapped.used
      # metrics:name=new.count
      # metrics:name=runnable.count
      # metrics:name=terminated.count
      # metrics:name=timed_waiting.count
      # metrics:name=unloaded
      # metrics:name=waiting.count

      - pattern: 'java.lang<name=(.+), type=GarbageCollector><>CollectionCount'
        name: 'jvm_gc_total'
        help: 'Total number of garbage collections'
        type: COUNTER
        labels:
          name: '$1'
      - pattern: 'java.lang<name=(.+), type=GarbageCollector><>CollectionTime'
        valueFactor: 0.001
        name: 'jvm_gc_time_seconds_total'
        help: 'Total time in seconds spent on garbage collections'
        type: COUNTER
        labels:
          name: '$1'
      - pattern: 'java.lang<name=(.+), type=GarbageCollector><LastGcInfo>duration'
        valueFactor: 0.000001
        name: 'jvm_gc_duration_seconds'
        help: 'Garbage collection duration in seconds'
        type: GAUGE
        labels:
          name: '$1'
      - pattern: 'java.lang<name=(.+), type=GarbageCollector><LastGcInfo>GcThreadCount'
        name: 'jvm_gc_threads'
        help: 'Garbage collection threads used'
        type: GAUGE
        labels:
          name: '$1'
      - pattern: 'java.lang<type=Memory><(Heap|NonHeap)MemoryUsage>(max|init|committed|used)'
        name: 'jvm_memory_$2_bytes'
        help: '$2 bytes in $1 memory'
        type: GAUGE
        labels:
          area: '$1'

      - pattern: 'java.lang<type=OperatingSystem><>AvailableProcessors'
        name: 'jvm_os_processors'
        help: 'Number of CPU cores available'
        type: GAUGE
      - pattern: 'java.lang<type=OperatingSystem><>(CommittedVirtualMemory|FreePhysicalMemory|TotalPhysicalMemory|FreeSwapSpace|TotalSwapSpace)Size'
        name: 'jvm_os_$1_bytes'
        help: '$1 in bytes'
        type: GAUGE
      - pattern: 'java.lang<type=OperatingSystem><>(Max|Open)FileDescriptorCount'
        name: 'jvm_os_$1_file_descriptors'
        help: '$1 file descriptors'
        type: GAUGE
      - pattern: 'java.lang<type=OperatingSystem><>(Process|System)CpuLoad'
        name: 'jvm_os_$1_cpu_load'
        help: '$1 cpu load'
        type: GAUGE
      - pattern: 'java.lang<type=OperatingSystem><>(Process|System)CpuTime'
        name: 'jvm_os_$1_cpu_time_seconds'
        help: '$1 cpu time in seconds'
        type: COUNTER
      - pattern: 'java.lang<type=OperatingSystem><>SystemLoadAverage'
        name: 'jvm_os_system_load_avg'
        help: 'System load average'
        type: GAUGE
      - pattern: 'java.lang<type=OperatingSystem><>(Arch|Name|Version): (.+)'
        name: 'jvm_os_info'
        value: 1
        help: 'A metric with constant 1 value labelled with OS information'
        type: GAUGE
        labels:
          '$1': '$2'
      - pattern: 'java.lang<type=Runtime><>Uptime'
        valueFactor: 0.001
        name: 'jvm_runtime_uptime_seconds'
        help: 'JVM uptime in seconds'
        type: COUNTER

      - pattern: 'java.lang<type=Threading><>(Daemon|Peak|TotalStarted|)ThreadCount'
        name: 'jvm_threading_$1_threads'
        help: 'JVM $1 thread count'
        type: GAUGE

      - pattern: 'java.nio<name=(.+), type=BufferPool><>Count'
        name: 'jvm_nio_buffer_pool_buffers'
        help: 'Number of buffers in NIO buffer pool'
        type: GAUGE
        labels:
          pool: '$1'
      - pattern: 'java.nio<name=(.+), type=BufferPool><>(MemoryUsed|TotalCapacity)'
        name: 'jvm_nio_buffer_pool_$2_bytes'
        help: 'NIO buffer pool $2 in bytes'
        type: GAUGE
        labels:
          pool: '$1'

{{- end }}
