controller:
  service:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: 35.240.252.23 # teko-warehouse-gw-ip
    annotations:
      # TODO: Create container-native load balancing
      # But now it only supports gce-ingress.
      # See: https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing
      cloud.google.com/neg: '{"ingress": true}'
