apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: foo.bar
spec:
  secretName: foo.bar-tls
  duration: 2160h     # 90d
  renewBefore: 360h   # 15d
  commonName: foo.bar
  dnsNames:
  - foo.bar
  - www.foo.bar
  issuerRef:
    name: ca-issuer
    kind: Issuer

# Issuing Certificates
# ref: https://docs.cert-manager.io/en/latest/tasks/issuing-certificates/index.html
