{{- $jaas := .Values.authn.frontend.jaas }}
{{- if and $jaas.enabled (or (index $jaas "jaas.conf") (index $jaas "user.props"))}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datahub.fullname" . }}-frontend-jaas
  labels:
    {{- include "datahub.frontend.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with get $jaas "jaas.conf" }}
  jaas.conf: |
    {{- . | nindent 4}}
  {{- end }}
  {{- with get $jaas "user.props" }}
  user.props: |
    {{- range . }}
    {{ .username }}:{{ .password }}{{ with .roles }},{{ . | join "," }}{{ end }}
    {{- end }}
  {{- end }}
{{- end }}
