httpServer:
  https:
    enabled: true
    port: 8443

ingress:
  enabled: true
  ingressClassName: contour
  hosts:
    - host: trino.local
      paths:
      - path: /

  tls:
  - secretName: trino.local-tls
    hosts:
      - trino.local
