cache:
  enabled: true

  persistence:
    enabled: true
    accessModes:
    - ReadWriteOnce
    size: 20Gi

spill:
  enabled: true
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-hdd
  size: 200Gi
