repositories:
- name: grafana
  url:  https://grafana.github.io/helm-charts

releases:
- name: grafana
  namespace: grafana
  chart: grafana/grafana
  version: 7.0.19
  values:
  - ./grafana.yaml.gotmpl
  - fullnameOverride: grafana
