---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "presto.fullname" . }}-catalog
  labels:
    {{- include "presto.labels" . | nindent 4 }}
data:
{{- range $catalog, $data := .Values.catalog }}
  {{ $catalog }}: |
    {{- $data | nindent 4 }}
{{- end }}
