{{- $presto := .Values.presto }}
{{- $config := index $presto "config.properties" }}

{{- $_ := include "dict-cleanup" $config }}
{{- $_ := set $config "http-server.http.port" 8080 }}
{{- $_ := unset $config "coordinator" }}
{{- $_ := unset $config "node-scheduler.include-coordinator" }}
{{- $_ := unset $config "discovery-server.enabled" }}
{{- $_ := unset $config "discovery.uri" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "presto.fullname" . }}-config
  labels:
    {{- include "presto.labels" . | nindent 4 }}
data:
  coordinator-config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=false
    discovery-server.enabled=true
    discovery.uri={{ printf "http://%s:8080" (include "presto.fullname" .) }}
    {{- range $key, $value := $config }}
    {{ $key }}={{ $value }}
    {{- end }}

  worker-config.properties: |
    coordinator=false
    discovery.uri={{ printf "http://%s:8080" (include "presto.fullname" .) }}
    {{- range $key, $value := $config }}
    {{ $key }}={{ $value }}
    {{- end }}
