{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "druid.historical.serviceAccountName" . }}
  labels:
    {{- include "druid.historical.labels" (list . nil) | nindent 4 }}
{{- end }}
