{{- range $group := .Values.historical }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "druid.fullname" $ }}-historical-{{ $group.tier }}
  labels:
    {{- include "druid.historical.labels" (list $ $group.tier) | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8083
    protocol: TCP
    targetPort: http
  selector:
    {{- include "druid.historical.selectorLabels" (list $ $group.tier) | nindent 4 }}
{{- end }}
