apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "buildkitd.fullname" . }}
  labels:
    {{- include "buildkitd.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "buildkitd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "buildkitd.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.rootless }}
        container.apparmor.security.beta.kubernetes.io/buildkitd: unconfined
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableServiceLinks: false
      containers:
        - name: buildkitd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config=/etc/buildkit/buildkitd.toml
            {{- if .Values.rootless }}
            - --oci-worker-no-process-sandbox
            {{- end }}
          ports:
            - name: buildkitd
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- with .Values.securityContext }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.rootless }}
            seccompProfile:
              type: Unconfined
            runAsUser: 1000
            runAsGroup: 1000
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/buildkit/
            {{- if .Values.rootless }}
            # Dockerfile has `VOLUME /home/user/.local/share/buildkit` by default too,
            # but the default VOLUME does not work with rootless on Google's Container-Optimized OS
            # as it is mounted with `nosuid,nodev`.
            # https://github.com/moby/buildkit/issues/879#issuecomment-1240347038
            - name: buildkitd
              mountPath: /home/user/.local/share/buildkit
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "buildkitd.fullname" . }}
        {{- if .Values.rootless }}
        - name: buildkitd
          emptyDir: {}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      terminationGracePeriodSeconds: 30
      serviceAccountName: {{ include "buildkitd.serviceAccountName" . }}
      priorityClassName:  {{ .Values.priorityClassName }}
      runtimeClassName:   {{ .Values.runtimeClassName }}
      schedulerName:      {{ .Values.schedulerName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
