{{- $scheduler := mergeOverwrite (deepCopy .Values.commons) .Values.scheduler -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airflow.fullname" . }}-scheduler
  labels:
    {{- include "airflow.scheduler.labels" . | nindent 4 }}
  annotations:
    {{- toYaml $scheduler.annotations | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "airflow.scheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "airflow.scheduler.selectorLabels" . | nindent 8 }}
      annotations:
        {{- with $scheduler.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "airflow.checksum" . | nindent 8 }}
    spec:
    {{- with .Values.image.pullSecret }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      enableServiceLinks: false
      containers:
      {{- if and (eq .Values.dags.fetcher "git") .Values.dags.git.sidecarContainer -}}
        {{- include "airflow.gitsync" . | nindent 8 }}
      {{- end }}
        - name: scheduler
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with $scheduler.command }}
          command:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with $scheduler.args }}
          args:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          env:
            {{- toYaml $scheduler.env | nindent 12 }}
          envFrom:
            - configMapRef:
                name: "{{ template "airflow.fullname" . }}-env"
          # Scheduler has no port & healcheck
          resources:
            {{- toYaml $scheduler.resources | nindent 12 }}
      serviceAccountName: {{ include "airflow.serviceAccountName" . }}
      priorityClassName:  {{ $scheduler.priorityClassName }}
      runtimeClassName:   {{ $scheduler.runtimeClassName }}
      schedulerName:      {{ $scheduler.schedulerName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if .Values.volumes }}
      volumes:
        {{- include "generic.volumes" . | nindent 8 }}
    {{- end }}
    {{- with $scheduler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $scheduler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $scheduler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
