apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "airflow.fullname" . }}-scheduler
  labels:
    {{- include "airflow.scheduler.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.scheduler.annotations | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "airflow.scheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "airflow.scheduler.selectorLabels" . | nindent 8 }}
      annotations:
        {{- with .Values.scheduler.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "airflow.checksum" . | nindent 8 }}
    spec:
    {{- with .Values.image.pullSecret }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      enableServiceLinks: false
      containers:
        - name: scheduler
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.scheduler.command }}
          command:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.scheduler.args }}
          args:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          env:
            {{- toYaml .Values.scheduler.env | nindent 12 }}
          envFrom:
            - configMapRef:
                name: "{{ template "airflow.fullname" . }}-env"
          # Scheduler has no port & healcheck
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
      serviceAccountName: {{ include "airflow.serviceAccountName" . }}
      priorityClassName:  {{ .Values.scheduler.priorityClassName }}
      runtimeClassName:   {{ .Values.scheduler.runtimeClassName }}
      schedulerName:      {{ .Values.scheduler.schedulerName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if .Values.volumes }}
      volumes:
        {{- include "generic.volumes" . | nindent 8 }}
    {{- end }}
    {{- with .Values.scheduler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.scheduler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.scheduler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
