{{- if and (eq (lower .Values.deploymentMode) "simplescalable") (.Values.proxy.enabled) }}
{{- $proxy := mergeOverwrite (deepCopy .Values.commons) .Values.proxy -}}
{{- $persistence := $proxy.persistence -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loki.fullname" . }}-proxy
  labels:
    {{- include "loki.proxy.labels" . | nindent 4 }}
    {{- with $proxy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml $proxy.annotations | nindent 4 }}
spec:
  replicas: {{ $proxy.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "loki.proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "loki.proxy.selectorLabels" . | nindent 8 }}
        {{- with $proxy.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- include "loki.proxy.checksum" . | nindent 8 }}
        {{- with $proxy.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $proxy.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableServiceLinks: false
      terminationGracePeriodSeconds: {{ $proxy.terminationPeriod }}
      containers:
        - name: loki-proxy
          image: {{ include "loki.proxy.image" $proxy.image | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -c
            - /etc/envoy/envoy-config.yaml
            {{- with .Values.proxy.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with $proxy.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $proxy.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3100
              protocol: TCP
          volumeMounts:
            {{- include "loki.proxy.volumeMounts" . | nindent 12 }}
            {{- with $proxy.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- with $proxy.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $proxy.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      serviceAccountName: {{ include "loki.serviceAccountName" . }}
      priorityClassName:  {{ $proxy.priorityClassName }}
      runtimeClassName:   {{ $proxy.runtimeClassName }}
      schedulerName:      {{ $proxy.schedulerName }}
      {{- with $proxy.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- include "loki.proxy.volumes" . | nindent 8 }}
        {{- with $proxy.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $proxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $proxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $proxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
