repositories:
- name: jupyterhub
  url:  https://jupyterhub.github.io/helm-chart

releases:
- name: jupyterhub
  namespace: jupyter
  chart: jupyterhub/jupyterhub
  version: 2.0.0
  values:
  - ./jupyterhub.yaml.gotmpl
  - ./db-postgres.yaml.gotmpl
  - ./auth-keycloak.yaml.gotmpl
  - fullnameOverride: jupyterhub
