apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-conf
data:
  spark-defaults.conf: |
    spark.driver.cores          2
    spark.driver.memory         4G
    spark.executor.cores        4
    spark.executor.memory       8G
    spark.deploy.defaultCores   8

    # spark.master                spark://spark.kites.rocks:7077
    # spark.master                yarn
    spark.master                k8s://https://kubernetes.default:443
    spark.submit.deployMode     client
    spark.scheduler.mode        FAIR

    spark.kubernetes.namespace        jupyter
    spark.kubernetes.container.image  gcr.io/spark-operator/spark:v2.4.4

    # spark.eventLog.enabled         true
    # spark.eventLog.dir             hdfs://hadoop.kites.rocks:8020/apps/spark/spark-events
    # spark.eventLog.compress        true
    # spark.history.ui.port          18081
    # spark.history.fs.logDirectory  hdfs://hadoop.kites.rocks:8020/apps/spark/spark-events

    # spark.shuffle.service.enabled  true
    # spark.shuffle.service.port     17337
