{{- $httpServer := .Values.httpServer }}
{{- $service := .Values.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trino.fullname" . }}
  labels:
    {{- include "trino.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $service.type }}
  {{- with $service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- if eq $service.type "LoadBalancer" }}
  {{- with $service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with $service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  {{- if not $service.allocateLoadBalancerNodePorts }}
  allocateLoadBalancerNodePorts: false
  {{- end }}
  {{- end }}
  {{- with $service.internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with $service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with $service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  {{- with $service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
  {{- if $httpServer.http.enabled }}
    - port: {{ $service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  {{- end }}
  {{- if $httpServer.https.enabled }}
    - port: {{ $service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
  {{- end }}
  {{- with $service.extraPorts }}
    {{- toYaml . | nindent 4}}
  {{- end }}
  selector:
    {{- include "trino.coordinator.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "trino.fullname" . }}-discovery
  labels:
    {{- include "trino.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
  {{- if $httpServer.http.enabled }}
    - port: {{ $service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  {{- end }}
  {{- if $httpServer.https.enabled }}
    - port: {{ $service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
  {{- end }}
  selector:
    {{- include "trino.coordinator.selectorLabels" . | nindent 4 }}
