{{- if and .Values.metrics.enabled .Values.metrics.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "mimir.fullname" . }}-metrics
  labels:
    {{- include "mimir.labels" . | nindent 4 }}
spec:
  podMetricsEndpoints:
  - port: http
    path: /metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "mimir.selectorLabels" . | nindent 6 }}
{{- end }}
