ingress:
  enabled: true
  ingressClassName: contour
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: superset.dungdm93.me
      path: /
  tls:
   - secretName: superset.dungdm93.me-tls
     hosts:
       - superset.dungdm93.me

flower:
  ingress:
    enabled: true
    ingressClassName: contour
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: superset.local
        path: /flower
    tls:
     - secretName: superset.local-tls
       hosts:
         - superset.local
