---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "superset.fullname" . }}-config
  labels:
    {{- include "superset.labels" . | nindent 4 }}
data:
  superset_config.py: |
    from cachelib.redis import RedisCache
    from celery.schedules import crontab

    LOG_LEVEL = 'DEBUG'

    SUPERSET_WEBSERVER_PROTOCOL = 'http'
    SUPERSET_WEBSERVER_ADDRESS = '0.0.0.0'
    SUPERSET_WEBSERVER_PORT = 8088
    ENABLE_PROXY_FIX = True
    SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:SuperSecr3t@postgres:5432/superset'
    WEBDRIVER_BASEURL = 'http://superset-webserver:8088/'

  gunicorn.conf.py: |
    accesslog = '-' # stdout
    errorlog = '-'  # stderr

  celeryconfig.py: |
