nameOverride: ""
fullnameOverride: ""

image:
  repository: grafana/tempo
  tag: 2.1.1
  pullPolicy: IfNotPresent
  pullSecrets: []

config:
  server:
    http_listen_port: 3200
    grpc_listen_port: 9095
    log_format: logfmt
    log_level: info
  distributor:
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      jaeger:
        protocols:
          grpc:
          thrift_http:
          thrift_binary:
          thrift_compact:
      zipkin:
      opencensus:
  metrics_generator:
    storage:
      path: /var/lib/tempo/metrics

ringKVStore:
  store: memberlist  # consul | etcd | inmemory | memberlist

  memberlist:
    bind_port: 7946

  # consul:
  # etcd:

storage:
  backend: local  # s3 | gcs | azure | local
  # s3:
  # gcs:
  # azure:
  # local:

  cache: null # redis | memcached
  # memcached:
  # redis:

  wal:
    path: /var/lib/tempo/wal
    v2_encoding: zstd
    search_encoding: snappy
  block:
    version: vParquet
    v2_encoding: zstd
    search_encoding: snappy

deploymentMode: AIO  # AIO | SimpleScalable

commons:
  replicas: null
  extraArgs: []

  labels: {}
  podLabels: {}
  annotations: {}
  podAnnotations: {}

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  schedulerName: null
  runtimeClassName: null
  priorityClassName: null

  affinity: {}
  tolerations: []
  nodeSelector: {}

  extraEnv: []
  extraEnvFrom: []
  extraVolumes: []
  extraVolumeMounts: []

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  podSecurityContext: {}
    # fsGroup: 2000

  podDisruptionBudget:
    enabled: false
    # minAvailable
    # maxUnavailable

  service:
    type: ClusterIP
    clusterIP:
    loadBalancerIP:
    loadBalancerClass:
    allocateLoadBalancerNodePorts: true
    nodePorts:
      http:
      grpc:
    sessionAffinity:
    sessionAffinityConfig:
    internalTrafficPolicy:
    externalTrafficPolicy:
    annotations: {}

## distributor + ingester
# write:
#   target: [write]
#   persistence:
#     enabled: false
#     storageClass: null
#     size: 10Gi
#     annotations: {}

## querier + query-frontend
# read:
#   target: [read]
#   autoscaling:
#     enabled: false
#     minReplicas: 1
#     maxReplicas: 100
#     metrics: []
#     # - type: Resource
#     #   resource:
#     #     name: cpu
#     #     target:
#     #       averageUtilization: 80

## alertmanager + compactor + ruler + store-gateway + query-scheduler
# backend:
#   target: [backend]
#   persistence:
#     enabled: false
#     storageClass: null
#     size: 10Gi
#     annotations: {}

serviceAccount:
  create: true
  annotations: {}
  name: ""
  automountServiceAccountToken: true
  imagePullSecrets: []

ingress:  # TODO
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

metrics:
  enabled: false
  podMonitor:
    enabled: false
