{{- if .Values.actionServiceAccount.role }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "datahub.fullname" . }}-actions
  labels:
    {{- include "datahub.actions.labels" . | nindent 4 }}
rules:
{{ toYaml .Values.actionServiceAccount.role }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "datahub.fullname" . }}
  labels:
    {{- include "datahub.actions.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "datahub.fullname" . }}-actions
subjects:
- kind: ServiceAccount
  name: {{ include "datahub.actions.serviceAccountName" . }}
{{- end }}
{{- if .Values.actionServiceAccount.clusterRole }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "datahub.fullname" . }}-actions
  labels:
    {{- include "datahub.actions.labels" . | nindent 4 }}
rules:
{{ toYaml .Values.actionServiceAccount.clusterRole }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "datahub.fullname" . }}
  labels:
    {{- include "datahub.actions.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "datahub.fullname" . }}-actions
subjects:
- kind: ServiceAccount
  name: {{ include "datahub.actions.serviceAccountName" . }}
{{- end }}
