{{ $env := dict }}
{{- $_ := set $env "DATAHUB_GMS_PROTOCOL" "http" }}
{{- include "datahub.setEnv" (list $env "DATAHUB_BASE_URL" .Values.frontend.baseUrl) }} # for extra actions

{{- $kafka := .Values.kafka }}
{{- if eq $kafka.schemaRegistry.type "CONFLUENT" -}}
  {{- $confluent := $kafka.confluent }}
  {{- $_ := set $env "SCHEMA_REGISTRY_URL" ($confluent.url | required "missing 'kafka.confluent.url'") }}
{{- end -}}

{{- include "datahub.setEnv" (list $env "EXECUTOR_ID" .Values.actions.ingestionExecutor.executorId) }}

{{- $slackAction := .Values.actions.slackAction }}
{{- $_ := set $env "DATAHUB_ACTIONS_SLACK_ENABLED" $slackAction.enabled }}
{{- if $slackAction.enabled }}
  {{- include "datahub.setEnv" (list $env "DATAHUB_ACTIONS_SLACK_DATAHUB_BASE_URL"         .Values.frontend.baseUrl) }}
  {{- include "datahub.setEnv" (list $env "DATAHUB_ACTIONS_SLACK_BOT_TOKEN"                $slackAction.botToken) }}
  {{- include "datahub.setEnv" (list $env "DATAHUB_ACTIONS_SLACK_SIGNING_SECRET"           $slackAction.signingSecret) }}
  {{- include "datahub.setEnv" (list $env "DATAHUB_ACTIONS_SLACK_CHANNEL"                  $slackAction.defaultChannel) }}
  {{- include "datahub.setEnv" (list $env "DATAHUB_ACTIONS_SLACK_SUPPRESS_SYSTEM_ACTIVITY" $slackAction.suppressSystemActivity) }}
{{- end }}

{{- $teamsAction := .Values.actions.teamsAction }}
{{- $_ := set $env "DATAHUB_ACTIONS_TEAMS_ENABLED" $teamsAction.enabled }}
{{- if $teamsAction.enabled }}
  {{- include "datahub.setEnv" (list $env "DATAHUB_ACTIONS_TEAMS_DATAHUB_BASE_URL"         .Values.frontend.baseUrl) }}
  {{- include "datahub.setEnv" (list $env "DATAHUB_ACTIONS_TEAMS_WEBHOOK_URL"              $teamsAction.webhookUrl) }}
  {{- include "datahub.setEnv" (list $env "DATAHUB_ACTIONS_TEAMS_SUPPRESS_SYSTEM_ACTIVITY" $teamsAction.suppressSystemActivity) }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datahub.fullname" . }}-actions
  labels:
    {{- include "datahub.actions.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := $env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
