{{- if .Values.actionServiceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "datahub.actions.serviceAccountName" . }}
  labels:
    {{- include "datahub.actions.labels" . | nindent 4 }}
  {{- with .Values.actionServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
