metrics:
  enabled: true

  serviceMonitor:
    enabled: true
    namespace:
    labels:
      foo: bar

    ## Additional serviceMonitor configs:
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: false
    metricRelabelings:
    - sourceLabels: [__meta_kubernetes_service_label_cluster]
      targetLabel: cluster
      regex: (.*)
      replacement: ${1}
      action: replace
