webserver_config: |
  import os
  from flask_appbuilder.security.manager import AUTH_OAUTH

  AUTH_TYPE = AUTH_OAUTH
  AUTH_USER_REGISTRATION = True
  AUTH_USER_REGISTRATION_ROLE = "Viewer"

  keycloak_endpoint = "http://keycloak:8080"
  keycloak_realm = "data"
