repositories:
- name: metrics-server
  url:  https://kubernetes-sigs.github.io/metrics-server

releases:
- name: metrics-server
  namespace: kube-system
  chart: metrics-server/metrics-server
  version: 3.11.0
  values:
  - ./metrics-server.yaml
  - fullnameOverride: metrics-server
