---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "druid.fullname" . }}-middlemanager
  labels:
    {{- include "druid.middlemanager.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8091
    protocol: TCP
    targetPort: http
  selector:
    {{- include "druid.middlemanager.selectorLabels" . | nindent 4 }}
